### PR TITLE
Build auto-config-brancher image with its binary

### PR DESCRIPTION
**Pull request by hongkailiu**
/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by thrasher-redhat** [comment]
Did you mean to tag @openshift/openshift-team-developer-productivity-test-platform ?

**Comment by hongkailiu** [comment]
@stevekuznetsov 
The current one dep. on https://github.com/openshift/ci-tools/pull/167 and https://github.com/openshift/release/pull/5105
right?

**Comment by stevekuznetsov** [comment]
Ah right

/hold

**Comment by hongkailiu** [comment]
> Did you mean to tag ... ?

Oops ...

**Pull request merged**
