### PR TITLE
Upgrade to go 1.18

### PR DESCRIPTION
**Pull request by hongkailiu**
/cc @openshift/test-platform

### CODE REVIEW

**Comment by smg247** [comment]
@hongkailiu we actually need this one so that `test-infra` can be bumped. Do you know how to fix the test failures?

**Comment by hongkailiu** [comment]
> @hongkailiu we actually need this one so that `test-infra` can be bumped. Do you know how to fix the test failures?

Tried several things yesterday. No luck.
I can reproduce it locally (with go 1.18) tough.

**Comment by smg247** [comment]
I think we can just change `pkg/html/html.go#51` to `if _, err := fmt.Fprint(w, pageEnd); err != nil {` now...

**Pull request merged**
