### PR TITLE
Revert "TRT-1627: Use variant registry for disruption and remove some outdated half implemented view management"

### PR DESCRIPTION
**Pull request by neisw**
Reverts openshift/ci-tools#4096

Seeing errors from job-table-updater

```
Creating jobs from releases
Priming jobs
Inserting 54 jobs
time="2024-05-16T18:30:06.673Z" level=fatal msg="Command failed" error="54 row insertions failed (insertion of row [insertID: \"zRq7MrrxXwJCZAY6gKhNxXx8aha\"; insertIndex: 0] failed with error: {Location: \"\"; Message: \"Missing required fields: Msg_0_CLOUD_QUERY_TABLE.architecture, Msg_0_CLOUD_QUERY_TABLE.fromrelease, Msg_0_CLOUD_QUERY_TABLE.ipmode, Msg_0_CLOUD_QUERY_TABLE.network, Msg_0_CLOUD_QUERY_TABLE.platform, Msg_0_CLOUD_QUERY_TABLE.release, Msg_0_CLOUD_QUERY_TABLE.runse2eparallel, Msg_0_CLOUD_QUERY_TABLE.runse2eserial, Msg_0_CLOUD_QUERY_TABLE.runsupgrade, Msg_0_CLOUD_QUERY_TABLE.topology.\"; Reason: \"invalid\"}, insertion of row [insertID: \"rdnOEFAiHAD0V6IkZI25IAjd8ua\"; insertIndex: 1] failed with error: {Location: \"\"; Message: \"Missing required fields: Msg_0_CLOUD_QUERY_TABLE.architecture, Msg_0_CLOUD_QUERY_TABLE.fromrelease, Msg_0_CLOUD_QUERY_TABLE.ipmode, Msg_0_CLOUD_QUERY_TABLE.network, Msg_0_CLOUD_QUERY_TABLE.platform, Msg_0_CLOUD_QUERY_TABLE.release, Msg_0_CLOUD_QUERY_TABLE.runse2eparallel, Msg_0_CLOUD_QUERY_TABLE.runse2eserial, Msg_0_CLOUD_QUERY_TABLE.runsupgrade, Msg_0_CLOUD_QUERY_TABLE.topology.\"; Reason: \"invalid\"}, insertion of row [insertID: \"8oRswDfSS6YwrMmAt5oZGVUiye0\"; insertIndex: 2] failed with error: {Location: \"\"; Message: \"Missing required fields: Msg_0_CLOUD_QUERY_TABLE.architecture, Msg_0_CLOUD_QUERY_TABLE.fromrelease, Msg_0_CLOUD_QUERY_TABLE.ipmode, Msg_0_CLOUD_QUERY_TABLE.network, Msg_0_CLOUD_QUERY_TABLE.platform, Msg_0_CLOUD_QUERY_TABLE.release, Msg_0_CLOUD_QUERY_TABLE.runse2eparallel, Msg_0_CLOUD_QUERY_TABLE.runse2eserial, Msg_0_CLOUD_QUERY_TABLE.runsupgrade, Msg_0_CLOUD_QUERY_TABLE.topology.\"; Reason: \"invalid\"}, ...)"
```

### CODE REVIEW

**Comment by dgoodwin** [comment]
/lgtm

look like the jobs table had required columns for the variants.

**Comment by neisw** [comment]
/hold
Consider https://github.com/openshift/ci-tools/pull/4128

**Pull request merged**
