### PR TITLE
Bump test-infra to bc8196c5c352

### PR DESCRIPTION
**Pull request by alvaroaleman**
Mostly to get https://github.com/kubernetes/test-infra/pull/20563

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by droslean** [comment]
We will need a follow-up to the release repo.

**Comment by alvaroaleman** [comment]
@droslean I know, I was planning on just triggering the autoconfigbrancher

**Comment by alvaroaleman** [comment]
@droslean mind tagging the PR?

**Review by droslean — APPROVED** [review]

**Pull request merged**
