### PR TITLE
test: migrate ci-operator integration tests

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Without changing `azure` to `azure4` I get errors like this: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_ci-tools/959/pull-ci-openshift-ci-tools-master-integration/1277321927014223872

How come we didn't hit this before? It was always wrong.

**Comment by stevekuznetsov** [comment]
Seeing this flake locally ...

```
[INFO] running integration suite ci-operator-configresolver
[INFO] Starting the config resolver...
[INFO] Waiting for the config resolver to be ready...
SUCCESS after 0.019s: hack/lib/integration.sh:70: executing 'curl http://127.0.0.1:8081/healthz/ready' expecting any result and text 'OK'; re-trying every 0.2s until completion or 60.000s
SUCCESS after 0.013s: test/integration/ci-operator-configresolver.sh:24: executing 'curl 'http://127.0.0.1:8080/config?org=openshift&repo=installer&branch=release-4.2' >/tmp/openshift/test-integration/actual/openshift-installer-release-4.2.json' expecting success
FAILURE after 0.009s: hack/lib/integration.sh:28: executing 'diff -Naupr --ignore-matching-lines 'startTime' --ignore-matching-lines 'name: \w\{8\}\(-\w\{4\}\)\{3\}-\w\{12\}' --ignore-matching-lines 'sha: \w\{40\}' /tmp/openshift/test-integration/actual/openshift-installer-release-4.2.json /home/stevekuznetsov/code/openshift/ci-tools/src/github.com/openshift/ci-tools/test/integration/ci-operator-configresolver//expected/openshift-installer-release-4.2.json' expecting success: the command returned the wrong error code
Standard output from the command:
--- /tmp/openshift/test-integration/actual/openshift-installer-release-4.2.json	2020-06-28 14:01:24.231731660 -0700
+++ /home/stevekuznetsov/code/openshift/ci-tools/src/github.com/openshift/ci-tools/test/integration/ci-operator-configresolver//expected/openshift-installer-release-4.2.json	2020-06-28 13:41:12.405021244 -0700
@@ -41,7 +41,7 @@
           {
             "as": "ipi-install-rbac",
             "from": "installer",
-            "commands": "setup-rbac-2\n",
+            "commands": "setup-rbac\n",
             "resources": {
               "requests": {
                 "cpu": "1000m",
@@ -52,13 +52,19 @@
           {
             "as": "ipi-install-install",
             "from": "installer",
-            "commands": "openshift-cluster install --newFlag\n",
+            "commands": "openshift-cluster install\n",
             "resources": {
               "requests": {
                 "cpu": "1000m",
                 "memory": "2Gi"
               }
-            }
+            },
+            "env": [
+              {
+                "name": "TEST_PARAMETER",
+                "default": "test parameter default"
+              }
+            ]
           }
         ],
         "test": [
@@ -108,7 +114,7 @@
           {
             "as": "ipi-install-rbac",
             "from": "installer",
-            "commands": "setup-rbac-2\n",
+            "commands": "setup-rbac\n",
             "resources": {
               "requests": {
                 "cpu": "1000m",
@@ -119,13 +125,19 @@
           {
             "as": "ipi-install-install",
             "from": "installer",
-            "commands": "openshift-cluster install --newFlag\n",
+            "commands": "openshift-cluster install\n",
             "resources": {
               "requests": {
                 "cpu": "1000m",
                 "memory": "2Gi"
               }
-            }
+            },
+            "env": [
+              {
+                "name": "TEST_PARAMETER",
+                "default": "test parameter default"
+              }
+            ]
           }
         ],
         "test": [
``` 

??

**Comment by stevekuznetsov** [comment]
Sometimes I see the configresolver tests fail to see an update ... wtf?

**Comment by stevekuznetsov** [comment]
Sometimes it takes 20s for an update to be reflected in the generation endpoint?

```
[INFO] Waiting for the config resolver to update...
SUCCESS after 13.751s: hack/lib/integration.sh:91: executing 'test $( os::integration::configresolver::generation::config ) -gt 80' expecting success; re-trying every 0.2s until completion or 60.000s
```

**Comment by stevekuznetsov** [comment]
@bbguimaraes I don't understand this failure. Somehow, I am only running some subset of the tests with the registry over HTTP while with `--registry` it works:

```
$ grep JOB_NAME_SAFE -A 2 /home/stevekuznetsov/code/openshift/ci-tools/src/github.com/openshift/ci-tools/test/integration/ci-operator//multi-stage/expected/installer.json | grep value | sort | uniq
              "value": "e2e-default"
              "value": "e2e-gcp"
              "value": "e2e-override-parameter"
              "value": "e2e-parameter"
$ grep JOB_NAME_SAFE -A 2 /tmp/openshift/test-integration/ci-operator/installer.json | grep value | sort | uniq
              "value": "e2e-azure"
              "value": "e2e-gcp"
```

This is the last test case in `test/integration/ci-operator.sh` for multi-stage.

**Comment by stevekuznetsov** [comment]
I guess [this](https://github.com/openshift/ci-tools/pull/959#issuecomment-650821401) is a failure with updating the registry and serving old data

**Comment by stevekuznetsov** [comment]
Sorry Alvaro, choosing a specific suite is useful ...

**Comment by stevekuznetsov** [comment]
Hm, now I am seeing 

```
2020/06/28 14:22:55 Loading configuration from http://127.0.0.1:8080 for openshift/installer@release-4.2
error: failed to load configuration: response from configresolver == 404 (Not Found)
```

**Comment by stevekuznetsov** [comment]
Hmm ok I had a rogue `ci-operator-configresolver` process leak out and hold on to 8080. Apparently starting a new `ci-operator-configresolver` process that can't bind does not fail...

```
$ cat _output/scripts/test-integration/logs/configresolver.log 
time="2020-06-28T14:28:41-07:00" level=info msg="Server exited." error="listen tcp :9090: bind: address already in use"
time="2020-06-28T14:28:41-07:00" level=info msg="Server exited." error="listen tcp :8081: bind: address already in use"
time="2020-06-28T14:28:41-07:00" level=info msg="Configs reloaded" duration=1.742704ms
time="2020-06-28T14:28:41-07:00" level=info msg="Registry reloaded" duration="921.716µs"
time="2020-06-28T14:28:41-07:00" level=info msg="Configs reloaded" duration=1.047615ms
time="2020-06-28T14:28:41-07:00" level=info msg="Server exited." error="listen tcp :8082: bind: address already in use"
time="2020-06-28T14:28:41-07:00" level=info msg="Server exited." error="listen tcp :8080: bind: address already in use"
time="2020-06-28T14:28:41-07:00" level=info msg="Registry reloaded" duration=1.393882ms
time="2020-06-28T14:28:41-07:00" level=info msg="Received signal." signal=terminated
time="2020-06-28T14:28:41-07:00" level=info msg="Server shutting down..."
time="2020-06-28T14:28:41-07:00" level=info msg="Server shutting down..."
time="2020-06-28T14:28:41-07:00" level=info msg="Worker shutting down..."
time="2020-06-28T14:28:41-07:00" level=info msg="Server shutting down..."
time="2020-06-28T14:28:41-07:00" level=info msg="Worker shutting down..."
time="2020-06-28T14:28:41-07:00" level=info msg="Server shutting down..."
time="2020-06-28T14:28:41-07:00" level=info msg="Interrupt received."
time="2020-06-28T14:28:41-07:00" level=info msg="All workers gracefully terminated, exiting."
time="2020-06-28T14:28:41-07:00" level=warning msg="failed to get config" branch=release-4.2 error="could not find any config for org openshift" org=openshift repo=installer variant=
time="2020-06-28T14:28:41-07:00" level=warning msg="failed to get config" branch=release-4.2 error="could not find any config for org openshift" org=openshift repo=installer variant=
```

**Comment by alvaroaleman** [comment]
> Sorry Alvaro, choosing a specific suite is useful ...

What are you talking about?

**Pull request merged**
