### PR TITLE
`payload-testing-prow-plugin`: introduce symlink watcher 

### PR DESCRIPTION
**Pull request by smg247**
I previously implemented https://github.com/openshift/ci-tools/pull/4325, which didn't solve the issue of constantly reloading configs. I noticed that the `dptp-controller-manager` [uses](https://github.com/openshift/ci-tools/pull/2805) a symlink watcher. It seems reasonable that the absence of this here is causing this issue.

For: https://issues.redhat.com/browse/DPTP-4172

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by smg247** [comment]
/override ci/prow/e2e
It flaked

**Pull request merged**
