### PR TITLE
`ci-operator`: Remove old promotion fields

### PR DESCRIPTION
**Pull request by danilo-gemoli**
New promotion targets feature has been introduced in https://github.com/openshift/ci-tools/pull/3858:
```yaml
promotion:
  to:
  - name: "target-1"
  - name: "target-2"
```
From that moment on I have slowly tried to migrate every `promotion:` stanza I could think of, from the old schema to the new one:
- https://github.com/openshift/release/pull/46931
- https://github.com/openshift/release/pull/46971
- https://github.com/openshift/ci-chat-bot/pull/444

Now it's the turn of this repository.

/cc @jmguzik @openshift/test-platform

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
@stevekuznetsov

**Comment by stevekuznetsov** [comment]
Nice!

**Pull request merged**
