### PR TITLE
Updates to ci-secret-generator

### PR DESCRIPTION
**Pull request by stevekuznetsov**
ci-secret-generator: run bash commands safely

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

ci-secret-generator: clean up errors

Before, illegible and not useful:
```
INFO[0030] processing attachment                         attachment=build01_ci_reg_auth_value.txt command="oc --as system:adsmin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | select(.type==\"kubernetes.io/dockercfg\") | select(.metadata.annotations[\"kubernetes.io/service-account.name\"]==\"default\") | .data[\".dockercfg\"]' --raw-output | base64 --decode | jq '.[\"docker-registry.default.svc:5000\"].auth' --raw-output | tr -d '\\\\n'" item=build_farm
ERRO[0031] oc --as system:adsmin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | select(.type=="kubernetes.io/dockercfg") | select(.metadata.annotations["kubernetes.io/service-account.name"]=="default") | .data[".dockercfg"]' --raw-output | base64 --decode | jq '.["docker-registry.default.svc:5000"].auth' --raw-output | tr -d '\\n': failed to generate attachment  error="command \"oc --as system:adsmin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | select(.type==\\\"kubernetes.io/dockercfg\\\") | select(.metadata.annotations[\\\"kubernetes.io/service-account.name\\\"]==\\\"default\\\") | .data[\\\".dockercfg\\\"]' --raw-output | base64 --decode | jq '.[\\\"docker-registry.default.svc:5000\\\"].auth' --raw-output | tr -d '\\\\\\\\n'\" failed, output- error: the server doesn't have a resource type \"secrets\"\n : exit status 1"
FATA[0031] Failed to update secrets.                     error="bwItem.ItemName: build_farm, bwItem.AttachmentName: build01_ci_reg_auth_value.txt, oc --as system:adsmin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | select(.type==\"kubernetes.io/dockercfg\") | select(.metadata.annotations[\"kubernetes.io/service-account.name\"]==\"default\") | .data[\".dockercfg\"]' --raw-output | base64 --decode | jq '.[\"docker-registry.default.svc:5000\"].auth' --raw-output | tr -d '\\\\n' failed: command \"oc --as system:adsmin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | select(.type==\\\"kubernetes.io/dockercfg\\\") | select(.metadata.annotations[\\\"kubernetes.io/service-account.name\\\"]==\\\"default\\\") | .data[\\\".dockercfg\\\"]' --raw-output | base64 --decode | jq '.[\\\"docker-registry.default.svc:5000\\\"].auth' --raw-output | tr -d '\\\\\\\\n'\" failed, output- error: the server doesn't have a resource type \"secrets\"\n : exit status 1"
```

After:
```
INFO[0000] Dry-Run enabled, writing secrets to /tmp/ci-secret-generator907763598
INFO[0000] processing attachment                         attachment=build01_ci_reg_auth_value.txt command="oc --as systems:admin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | select(.type==\"kubernetes.io/dockercfg\") | select(.metadata.annotations[\"kubernetes.io/service-account.name\"]==\"default\") | .data[\".dockercfg\"]' --raw-output | base64 --decode | jq '.[\"docker-registry.default.svc:5000\"].auth' --raw-output | tr -d '\\\\n'" item=build_farm
ERRO[0000] failed to generate attachment                 attachment=build01_ci_reg_auth_value.txt command="oc --as systems:admin --context api.ci get secrets --namespace ocp -o json | jq '.items[] | select(.type==\"kubernetes.io/dockercfg\") | select(.metadata.annotations[\"kubernetes.io/service-account.name\"]==\"default\") | .data[\".dockercfg\"]' --raw-output | base64 --decode | jq '.[\"docker-registry.default.svc:5000\"].auth' --raw-output | tr -d '\\\\n'" error="Error from server (Forbidden): users \"systems:admin\" is forbidden: User \"stevekuznetsov\" cannot impersonate users at the cluster scope: no RBAC policy matched\n : exit status 1" item=build_farm
FATA[0000] Failed to update secrets.                     error="failed to generate attachment"
```

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

ci-secret-generator: allow validating output

We want to know that the secret values we're about to put into BitWarden
are actually used somewhere - namely, that the ci-secret-bootstrap tool
will read them out and use them in the clusters.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
For the last commit ... before:

```
$ ci-secret-generator --bootstrap-config /home/stevekuznetsov/code/openshift/release/src/github.com/openshift/release/core-services/ci-secret-bootstrap/_config.yaml --bw-password-path ~/secrets/bitwarden-password.txt --bw-user skuznets@redhat.com --concurrency 300 --dry-run=false --config /home/stevekuznetsov/code/openshift/release/src/github.com/openshift/release/core-services/ci-secret-generator/_config.yaml
ERRO[0000] bw cmd failed: , exit status 1                error="exit status 1"
FATA[0000] failed to get Bitwarden client.               error="exit status 1"
```

Now:

```
$ ci-secret-generator --bootstrap-config /home/stevekuznetsov/code/openshift/release/src/github.com/openshift/release/core-services/ci-secret-bootstrap/_config.yaml --bw-password-path ~/secrets/bitwarden-password.txt --bw-user skuznets@redhat.com --concurrency 300 --dry-run=false --config /home/stevekuznetsov/code/openshift/release/src/github.com/openshift/release/core-services/ci-secret-generator/_config.yaml
ERRO[0000] bitwarden command failed                      args="[login skuznets@redhat.com CENSORED --response]" error="exit status 1" stderr="{\"success\":false,\"message\":\"You are already logged in as skuznets@redhat.com.\"}" stdout=
FATA[0000] failed to get Bitwarden client.               error="failed to log in: exit status 1"
```

**Pull request merged**
