### PR TITLE
Bump test-infra

### PR DESCRIPTION
**Pull request by stevekuznetsov**
use new bumper import path

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

bump test-infra

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

---

Requires https://github.com/openshift/release-controller/pull/259

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Damn, that was involved :eyeroll:

**Comment by stevekuznetsov** [comment]
Needs https://github.com/openshift/release-controller/pull/259 and https://github.com/openshift/ci-chat-bot/pull/144

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
