### PR TITLE
Allow rehearsing jobs with multiple branches

### PR DESCRIPTION
**Pull request by droslean**
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>
/cc @openshift/openshift-team-developer-productivity-platform-maintainers

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
What does this need?

**Comment by petr-muller** [comment]
I think I can make rehearsals smarter to properly address https://github.com/openshift/ci-tools/pull/2136

**Pull request closed without merging**
