### PR TITLE
Add GCP arm64 cluster profile: gcp-arm64

### PR DESCRIPTION
**Pull request by SaravanaStorageNetwork**
This PR is to add a new profile for GCP ARM 
Ref: [ARMOCP-563](https://issues.redhat.com/browse/ARMOCP-563)

### CODE REVIEW

**Comment by SaravanaStorageNetwork** [comment]
@deepsm007 PTAL

**Comment by Prashanth684** [comment]
lgtm . i'll wait for Deep to review and add it officially.

**Comment by deepsm007** [comment]
/lgtm
Please add description and/or Jira

**Comment by psalajova** [comment]
Please also don't forget to [add boskos leases](https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#adding-new-leases)

**Pull request merged**
