### PR TITLE
prowgen: use flag --report-credentials-file

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1970

require https://github.com/openshift/ci-tools/pull/1695

/hold

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
Rehearsal (based on https://github.com/openshift/release/pull/16074) works.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/16074/rehearse-16074-pull-ci-openshift-ci-tools-master-unit/1362853095721144320#1:build-log.txt%3A30

**Review by stevekuznetsov — APPROVED** [review]

**Pull request merged**
