### PR TITLE
webreg: document different types of jobs and how to configure them

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @bparees @smarterclayton @petr-muller

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Will be here: 

server-ci-tools-555.svc.ci.openshift.org/help/ci-operator#test-types

**Comment by bbguimaraes** [comment]
/lgtm
/hold

for extra reviews.

**Pull request merged**
