### PR TITLE
prowgen: resolve configuration

### PR DESCRIPTION
**Pull request by bbguimaraes**
/hold

Requires: https://github.com/openshift/release/pull/8846.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Double hold, `hack/validate-generated-config.sh` will need to be updated and can't use `--from-release-repo`.

**Comment by petr-muller** [comment]
Curious, we does prowgen need to resolve the config?

**Comment by petr-muller** [comment]
/test all

(I need to test something)

**Comment by stevekuznetsov** [comment]
I don't think we will need this

/close

**Pull request closed without merging**
