### PR TITLE
Update test-infra and k8s.io/* dependencies

### PR DESCRIPTION
**Pull request by alvaroaleman**
Downstream follow-up to https://github.com/kubernetes/test-infra/pull/17869
Its a big changeset because the signature of the generated clients was changed

/label tide/merge-method-squash

### CODE REVIEW

**Comment by droslean** [comment]
@alvaroaleman We need a follow-up PR to make the changes also in the `openshift/release` repo as well.

**Comment by alvaroaleman** [comment]
@droslean I know, the autoconfigbrancher job will take care

**Comment by droslean** [comment]
@alvaroaleman Ok let's merge this and after the images will be built we can rerun the `autoconfigbrancher` job

**Pull request merged**
