### PR TITLE
azurestack: Add azurestack cluster profile for CI tests

### PR DESCRIPTION
**Pull request by rna-afk**
Adding azurestack cluster profile for e2e-azurestack tests in CI.

### CODE REVIEW

**Comment by patrickdillon** [comment]
I'm not very familiar with the cluster profiles but cargo culting off of #2097 it looks like we also need an entry here:
https://github.com/openshift/ci-tools/blob/master/cmd/repo-init/main.go#L634

And that would tie in with the steps configuration

**Comment by patrickdillon** [comment]
For context, Azure Stack is an on-prem variant of Azure. So for CI we will have an azure stack environment separate from our public azure environment.

**Comment by petr-muller** [comment]
@rna-afk looks liike you amended your changes to a merge commit, can you please clean it up?

**Comment by rna-afk** [comment]
My bad. Fixed it thanks.

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
