### PR TITLE
OSASINFRA-3477: openstack: Remove legacy location for OpenStack periodics from Sippy

### PR DESCRIPTION
**Pull request by pierreprinetti**
A follow-up to https://github.com/openshift/ci-tools/pull/4182

Depends on https://github.com/openshift/release/pull/53236

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/hold cancel
Jobs have moved; it is now fine to merge this.

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
