### PR TITLE
Better snyk code outputs

### PR DESCRIPTION
**Pull request by bear-redhat**
Improve `snyk-code` output to show newly discovered vulnerabilities fingerprints
Save vulnerabilities report to artifacts

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by droslean** [comment]
Do we need to address https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2913/pull-ci-openshift-release-snyk-deps/1551576963439661056#1:build-log.txt%3A5 in this PR?

**Comment by bear-redhat** [comment]
> Do we need to address https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2913/pull-ci-openshift-release-snyk-deps/1551576963439661056#1:build-log.txt%3A5 in this PR?

thats another issue we need to address, ill add the ignore today in a separate PR.

**Pull request merged**
