### PR TITLE
ci-operator: subsume tag_specification into releases

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Now, we will have one, explicit, straightfoward mechanism for adding
releases to a test configuration.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Part of [DPTP-2431](https://issues.redhat.com/browse/DPTP-2431)
/cc @openshift/test-platform 
/assign @emilvberglind @petr-muller

### CODE REVIEW

**Comment by emilvberglind** [comment]
From what I can discern, this seems to make sense.

**Comment by stevekuznetsov** [comment]
Fixed unit test issue, the e2e was a flake I think

**Comment by stevekuznetsov** [comment]
Wait no those e2e are real :(*

**Pull request merged**
