### PR TITLE
Specify the full name of ci-operator image

### PR DESCRIPTION
**Pull request by hongkailiu**
/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold 

@petr-muller @stevekuznetsov 

In order to run pods on any build cluter ... I think the full name of image is required.
What is the best way of doing this?

**Comment by petr-muller** [comment]
I think this is acceptable (explicit is good). The alternative would be to keep an ImageStream tracking these images on each build cluster, which feels "cleaner". /shrug

**Comment by hongkailiu** [comment]
> I think this is acceptable (explicit is good). The alternative would be to keep an ImageStream tracking these images on each build cluster, which feels "cleaner". /shrug

ImageStream sounds like a better idea. Let me give it a try with auto schedule.
https://docs.openshift.com/container-platform/3.11/architecture/core_concepts/builds_and_image_streams.html#image-streams

**Comment by hongkailiu** [comment]
/close
in favor of https://github.com/openshift/release/pull/5825

**Pull request closed without merging**
