### PR TITLE
chore(SRVKP-3752): add cluster profile for OpenShift Pipelines performance testing on AWS

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by jhutar** [comment]
Hello @psalajova . Could you please help me with `ci/prow/security` failure? I do not think mine PR could cause issues mentioned there. I'm pinging you directly just because I can see you in https://github.com/openshift/ci-tools/pull/3699 and I have that PR as a template for my work.

**Comment by psalajova** [comment]
@jhutar hi, yes the security job is not failing because of your changes, it's something we need to fix on our end. But it won't block the merge as it is an optional test

/approve

**Comment by jhutar** [comment]
Hello @psalajova ! Looks like `ci/prow/security` failure is blocking merge (looking at "Your PR dashboard."). Is there something you can do to workaround it?

**Pull request merged**
