### PR TITLE
Update test-infra to 0757032ed149

### PR DESCRIPTION
**Pull request by alvaroaleman**
Ref https://issues.redhat.com/browse/DPTP-2363

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Needs:
* https://github.com/openshift/ci-chat-bot/pull/192
* https://github.com/openshift/release-controller/pull/297

**Comment by stevekuznetsov** [comment]
```
 # github.com/openshift/ci-tools/cmd/autoconfigbrancher
cmd/autoconfigbrancher/main.go:129:9: undefined: secret.Agent
cmd/autoconfigbrancher/main.go:134:41: too many arguments in call to o.GitHubOptions.GitHubClient 
```

**Comment by alvaroaleman** [comment]
yeah failure is genuine I am  on it

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
