### PR TITLE
Use app.ci configresolver

### PR DESCRIPTION
**Pull request by alvaroaleman**
/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Its interesting how this doesn't can be just changed without adjusting any test.

**Comment by bbguimaraes** [comment]
> Its interesting how this doesn't can be just changed without adjusting any test.

We rely on the default value everywhere, and don't usually test argument treatment directly.

/retest

**Comment by alvaroaleman** [comment]
> We rely on the default value everywhere, and don't usually test argument treatment directly.

I guess it mostly confuses me because there is a set of fixtures that has the url. But maybe they are just stale?
/hold cancel

**Pull request merged**
