### PR TITLE
Improve the tags for the pruner

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-4041

/cc @openshift/test-platform @jupierce 

/hold

Will watch the rolling

### CODE REVIEW

**Comment by hongkailiu** [comment]
Doing a rehearsal with the built image.

```
$ oc image mirror registry.build10.ci.openshift.org/ci-op-m8nnqddf/pipeline@sha256:ace4d4a64f954d86a819a6c0969df2bcf892e047df5fa0decf6a9b17f2676d1a registry.ci.openshift.org/ci/hongkliu-test:ci-op-305ac7855dfea874f7d29d0afb58c76e0589d954 -a /tmp/b10.p.c
```

**Comment by deepsm007** [comment]
[rehearsal job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-lightspeed-service-main-images/1798737245503492096) with the new image 

Verified the promoted images from Quay

 
Screenshot from 2024-06-06 11-40-43
Screenshot from 2024-06-06 11-39-04

**Comment by deepsm007** [comment]
2nd test worked with ci-tools https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-ci-tools-master-images/1799016694375518208

**Comment by hongkailiu** [comment]
> 2nd test worked with ci-tools https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-openshift-ci-tools-master-images/1799016694375518208

[The cmd executed in the pod](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/branch-ci-openshift-ci-tools-master-images/1799016694375518208/artifacts/build-resources/pods.json) looks good to me and they are on QCI.
Screenshot 2024-06-07 at 9 07 30 AM

**Pull request merged**
