### PR TITLE
pod-scaler: ignore NaN values from Prometheus

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @openshift/openshift-team-developer-productivity-test-platform

Part of [DPTP-2349](https://issues.redhat.com/browse/DPTP-2349)

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
(the forthcoming e2e tests for this, it is simply not feasible to test this at a unit level since it depends on Prometheus query API behavior)

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
