### PR TITLE
ci-operator: log the configresolver fetch if we do it

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @AlexNPavel @bbguimaraes

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
 [INFO] Running test with ci-operator-configresolver
parse error: Invalid numeric literal at line 1, column 8
ERROR: ci-operator failed. 
```

WTF?

/retest

**Comment by bbguimaraes** [comment]
> ```
>  [INFO] Running test with ci-operator-configresolver
> parse error: Invalid numeric literal at line 1, column 8
> ERROR: ci-operator failed. 
> ```

You're messing with the dry-run output, which we use in integration tests. I think `log` instead of `fmt` is what we use in all other places because it goes to `stderr`.

**Comment by stevekuznetsov** [comment]
Fixed

**Pull request merged**
