### PR TITLE
webreg: add metadata based info to web UI

### PR DESCRIPTION
**Pull request by AlexNPavel**
This PR adds github links and owner information for all registry
components in the `configresolver` web UI using the registry metadata.

This PR also exposes the registry component suffixes and replaces all
hardcoded suffix values across all packages with the exposed consts to
prevent typos and make potential future refactors easier.

### CODE REVIEW

**Comment by AlexNPavel** [comment]
This depends on the registry metadata generation being enabled in `openshift/release`, so I will put a hold on this PR until that's all set up.

/hold

**Comment by stevekuznetsov** [comment]
Have you deployed a server to view the changes?

**Comment by AlexNPavel** [comment]
Link to server for this PR: https://server-ci-tools-1043.apps.ci.l2s4.p1.openshiftapps.com/

**Pull request merged**
