### PR TITLE
Add a test image with boskos

### PR DESCRIPTION
**Pull request by bbguimaraes**

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]

**Comment by alvaroaleman** [comment]
Out of curiosity, why not just use the `gcr.io/k8s-staging-boskos/boskos` image?

**Comment by bbguimaraes** [comment]
> Out of curiosity, why not just use the `gcr.io/k8s-staging-boskos/boskos` image?

See https://github.com/openshift/release/pull/11878 for the purpose.

**Comment by stevekuznetsov** [comment]
Part of DPTP-1365

**Pull request merged**
