### PR TITLE
prowgen: generate flag --lease-server-credentials-file

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1913

/hold

require

https://github.com/openshift/ci-tools/pull/1675

### CODE REVIEW

**Comment by hongkailiu** [comment]
rehearsal from https://github.com/openshift/release/pull/15701 seems working.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15701/rehearse-15701-pull-ci-openshift-origin-release-4.7-e2e-aws/1359144533731840000#1:build-log.txt%3A45

**Comment by petr-muller** [comment]
@hongkailiu 

Why don't we do something like "credentials file" that would contain something like `username:password`? Having separate files for username and password seems clunky...

**Comment by hongkailiu** [comment]
> @hongkailiu
> 
> Why don't we do something like "credentials file" that would contain something like `username:password`? Having separate files for username and password seems clunky...

Let me give it a try.

**Comment by alvaroaleman** [comment]
> Not trivial to me.

Whats not trivial about colon splitting a string and putting the second half into a closure that returns a bite slice?

**Comment by hongkailiu** [comment]
> > Not trivial to me.
> 
> Whats not trivial about colon splitting a string and putting the second half into a closure that returns a byte slice?

Let me try the 2nd time. :)

**Comment by hongkailiu** [comment]
Tested with
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15701/rehearse-15701-pull-ci-openshift-origin-release-4.7-e2e-aws/1360004912829698048
which is from
https://github.com/openshift/release/pull/15701

**Review by alvaroaleman — APPROVED** [review]

**Review by alvaroaleman — APPROVED** [review]

**Comment by hongkailiu** [comment]
The rehearse passed with the latest code.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/15701/rehearse-15701-pull-ci-openshift-origin-release-4.7-e2e-aws/1360235572890701824#1:build-log.txt%3A46

**Pull request merged**
