### PR TITLE
SUSTAINING-345: Add new profile for azure-sustaining-autorelease-412

### PR DESCRIPTION
**Pull request by san7ket**

### CODE REVIEW

**Comment by san7ket** [comment]
@smg247 Could you share a few pointers to help me better understand the CI failures? Any guidance would be greatly appreciated.

**Comment by smg247** [comment]
> @smg247 Could you share a few pointers to help me better understand the CI failures? Any guidance would be greatly appreciated.

Sorry, just saw this. Looks like everything is good now, and I have approved it.

**Pull request merged**
