### PR TITLE
secret-wrapper: populate a unique, writable KUBECONFIG

### PR DESCRIPTION
**Pull request by stevekuznetsov**
As we upload `$KUBECONFIG` as soon as it's available and some consumers
of the `$SHARED_DIR` (observers) will want to be able to consume it as
soon as it's uploaded, we need to handle the case where it does not
exist at the moment that a process starts reading the `$SHARED_DIR`, and
furthermore we can handle the creation of a unique, writeable copy of
the `$KUBECONFIG` for every consumer.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @bbguimaraes 
/cc @alvaroaleman 

follow-up to #1691

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Needed for DPTP-1668

**Comment by bbguimaraes** [comment]
LGTM

**Pull request merged**
