### PR TITLE
pod-scaler: correctly format output logs

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Some new feature in GoLand is making imports do the wrong thing and holy moly it's annoying

**Comment by petr-muller** [comment]
> Some new feature in GoLand is making imports do the wrong thing and holy moly it's annoying

Right? I hit it today too!

**Pull request merged**
