### PR TITLE
e2e: move lease tests over to Go

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Not sure what's broken in the template test ...

```
        2020/12/22 15:44:32 Container test in pod template completed successfully
        2020/12/22 15:44:32 Pod template succeeded after 3s
        2020/12/22 15:58:18 error: Process interrupted with signal interrupt, cancelling execution...
```

**Comment by stevekuznetsov** [comment]
yeah, reproducing this weird issue in the test. @bbguimaraes maybe you understand why?

```
        2020/12/28 17:55:51 Running pod template
        2020/12/28 17:55:56 Container test in pod template completed successfully
        2020/12/28 17:55:56 Pod template succeeded after 4s
// ...
        2020/12/28 18:34:45 error: Process interrupted with signal interrupt, cancelling execution...
        2020/12/28 18:34:45 cleanup: Deleting template template 
```

**Comment by stevekuznetsov** [comment]
of course. artifact gather. ugh

**Comment by stevekuznetsov** [comment]
Should be ready for review now

**Comment by stevekuznetsov** [comment]
Before:

```
 2020/12/17 20:44:38 Pod e2e-e2e succeeded after 1h17m16s 
```

After:

```
 2021/01/02 19:55:51 Pod e2e-e2e succeeded after 21m29s 
```

Quite a lot of time could also be saved if we figured out incremental builds and the optional operator test.

**Review by droslean — APPROVED** [review]

**Comment by droslean** [comment]
Holding. The `unit` job started to fail after I approved the PR.

**Comment by stevekuznetsov** [comment]
ffs

**Pull request merged**
