### PR TITLE
Upgrade version of k8s.io/test-infra

### PR DESCRIPTION
**Pull request by hongkailiu**
We would like to reuse the function defined in https://github.com/kubernetes/test-infra/pull/13805

After
https://github.com/kubernetes/test-infra/pull/13564

We have `rerun_auth_config: {}` in the `prowjob`.

### CODE REVIEW

**Comment by hongkailiu** [comment]
/assign @droslean 

```
$ GO111MODULE=on go get -v -u k8s.io/test-infra
...
go get: error loading module requirements
```

The current PR is the result without `-u`

Maybe I did not do it right?

**Comment by droslean** [comment]
locally the tests are working :/

**Comment by droslean** [comment]
@hongkailiu @stevekuznetsov We need to use `1.12` version to make the new deps to work.

**Pull request merged**
