### PR TITLE
Add new cluster profiles for Telco5G and PTP jobs

### PR DESCRIPTION
**Pull request by sshnaidm**
fyi @nishant-parekh @wking

### CODE REVIEW

**Comment by sshnaidm** [comment]
@psalajova please merge, thanks!

**Comment by psalajova** [comment]
/lgtm
Please don't forget to create the PR in the openshift/release repo for the credentials and boskos leases (https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#adding-a-new-cluster-profile) if you already haven't done so.

**Pull request merged**
