### PR TITLE
e2e: various minor fixes

### PR DESCRIPTION
**Pull request by bbguimaraes**

### CODE REVIEW

**Review by petr-muller — COMMENTED** [review]
/lgtm

(I know this is still WIP, I want to have a mark when I look next time :) )

**Review by petr-muller — APPROVED** [review]

**Comment by bbguimaraes** [comment]
Rebased.

**Review by petr-muller — APPROVED** [review]

**Comment by bbguimaraes** [comment]
https://issues.redhat.com/browse/DPTP-1365

**Pull request merged**
