### PR TITLE
Shard validator: shard job-config-master further (by job type)

### PR DESCRIPTION
**Pull request by petr-muller**
/cc @stevekuznetsov @hongkailiu @droslean @bbguimaraes

### CODE REVIEW

**Comment by droslean** [comment]
/hold 

Did you test this?

**Comment by petr-muller** [comment]
> Did you test this?

Kinda.

1. I changed/added unit tests
2. I checked it fails on master HEAD of openshift/release (which I would expect)
3. I checked it passes on https://github.com/openshift/release/pull/4105 (which it is supposed to)

**Pull request merged**
