### PR TITLE
Add option to enter source bug

### PR DESCRIPTION
**Pull request by GeoBK**
Add a dropdown listing the possible bugs from which the new clone
can be created to ease the process of creating clones by being
able to easily specify the dependency of the new clone.

### CODE REVIEW

**Comment by GeoBK** [comment]
cc @alvaroaleman

**Comment by alvaroaleman** [comment]
Wouldn't it make more sense to add a `clone` button to the table?

**Comment by GeoBK** [comment]
Do you mean one clone button for every entry in the table?

**Comment by alvaroaleman** [comment]
> Do you mean one clone button for every entry in the table?

Yes

**Comment by GeoBK** [comment]
I dont have any strong opinions either way, an additional dropdown was what was requested in the feedback document, but I can do it the other way as well. lmk if you feel this is the way to go.

**Comment by stevekuznetsov** [comment]
For any given target release, isn't there just one possible bug that can be the source of the clone? If so, we should just make the current clone drop-down do the right thing every time.

**Pull request closed without merging**
