### PR TITLE
Upgrade k8s.io/test-infra

### PR DESCRIPTION
**Pull request by hongkailiu**
Required by https://github.com/openshift/ci-tools/pull/115

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@hongkailiu please rebase
/lgtm

**Comment by stevekuznetsov** [comment]
/hold

Unclear why the needs-rebase bot isn't working here

**Comment by hongkailiu** [comment]
rebase: done.

**Comment by hongkailiu** [comment]
`make validate-vendor` stops working.
Using same version of go (1.12.9) results in different results on local PC and docker container.
Strange.

**Pull request merged**
