### PR TITLE
[CVP-1467] add support for the kube objects

### PR DESCRIPTION
**Pull request by jsztuka**
Creation of optional parameter PYXIS_URL that will be used in newly created step `optional-operators-cvp-common-apply-secrets` in o/release.
I'm not 100% sure if this is the correct way of implementing the variable in the new way.

### CODE REVIEW

**Comment by jsztuka** [comment]
@petr-muller can you please confirm/deny the way that the `OOPyxisUrl` variable is implemented?
Will be the variable `OOPyxisUrl` accessible in o/release steps?

**Comment by petr-muller** [comment]
@jsztuka so, again. please hold on until we make the full switch to multi-stage parameters. The step needs to have such multi-stage parameter (https://docs.ci.openshift.org/docs/architecture/step-registry/#parameters), then cvp-trigger can set its value when triggering the jobs.

**Comment by petr-muller** [comment]
@emilvberglind works on the switch

**Pull request closed without merging**
