### PR TITLE
Add payload job types for sippy to use to generate testgrid url

### PR DESCRIPTION
**Pull request by xueqzhan**
[TRT-714](https://issues.redhat.com/browse/TRT-714)

### CODE REVIEW

**Comment by stbenjam** [comment]
/test e2e

The e2e job seems broken it's looking for a 4.5 release?

**Comment by xueqzhan** [comment]
> /retest-required

Don't think it is related to my change. PRs in the same repo all have the same issue.

**Comment by stbenjam** [comment]
Maybe https://github.com/openshift/ci-tools/pull/3202 will fix it

**Comment by xueqzhan** [comment]
> Maybe #3202 will fix it

Good catch. I assumed it was a temporary image source issue.

**Pull request merged**
