### PR TITLE
Create QE dedicated GCP cluster profile "gcp-qe"

### PR DESCRIPTION
**Pull request by jianli-wei**
After discuss with DPP and Installer dev team, QE should use our dedicated cluster profiles.

release openshift/release#27067

Profile | Profile String | Cloud Type
-- | -- | --
ClusterProfileGCPQE | gcp-qe | gcp

### CODE REVIEW

**Comment by petr-muller** [comment]
@jianli-wei please stop assigning me on PR, assignments to PRs are automated and already happened. Additional pings just amplify notification noise. Also, please submit PRs with reasonable subjects and commit messages. You would not send a PR with `gcp-qe` subject to an open source project upstream, why do you think it's fine to do so on our repository?

**Comment by jianli-wei** [comment]
> @jianli-wei please stop assigning me on PR, assignments to PRs are automated and already happened. Additional pings just amplify notification noise. Also, please submit PRs with reasonable subjects and commit messages. You would not send a PR with `gcp-qe` subject to an open source project upstream, why do you think it's fine to do so on our repository?

Sorry, my bad. Just updated the subject slimiar to https://github.com/openshift/ci-tools/pull/2724. Thanks!

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
