### PR TITLE
Add signoff to autoowners

### LINKED ISSUE #787: autoowners: add signoff option
There should be an option to use the signoff feature for the created commit. 

The test-infra dco plugin that we use for kubevirt org does not have the option to whitelist the bot explicitly. Therefore dco check fails on the created PR.

We fixed that by amending the commit with a signoff and re-pushing it again. https://github.com/kubevirt/project-infra/pull/429/files#diff-e0a716b1a6d9204c23041c4e82ea7360R178

### PR DESCRIPTION
**Pull request by dhiller**
In order to avoid failing the DCO check we want to have a proper signoff on the created commit.

PR to change bumper in test-infra: kubernetes/test-infra#20360

Previous PR: openshift/ci-tools#795

Fixes #787

### CODE REVIEW

**Comment by dhiller** [comment]
@alvaroaleman I don't get how the [breaking-changes check failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1561/pull-ci-openshift-ci-tools-master-breaking-changes/1346061970750574592#1:build-log.txt%3A66) is related to the changes I introduced, can you help explain what I need to do?

**Comment by alvaroaleman** [comment]
@dhiller its because of the t-i bump: https://github.com/openshift/ci-tools/pull/1561/files#diff-e0a8c02a37a93ae8b44b0434660614c7b38be40ffe01477dd2c42c2b5787ff2dR87-R99

**Comment by alvaroaleman** [comment]
@dhiller that test isn't mandatory though but the integration one is and its failure is genuine, can you run:
```
make install
make update-integration
```
? That should fix it

**Pull request merged**
