### PR TITLE
Fix promotion for release jobs

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://coreos.slack.com/archives/CJARLA942/p1612917460409000?thread_ts=1612465277.308800&cid=CJARLA942

To handle the promotion from
https://prow.ci.openshift.org/view/gcs/origin-ci-test/logs/promote-release-openshift-machine-os-content-e2e-aws-4.7/1359240250689327104

/cc @openshift/openshift-team-developer-productivity-test-platform @smarterclayton

### CODE REVIEW

**Comment by hongkailiu** [comment]
What was broken:

From the promotion pod of the job:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/branch-ci-openshift-ci-tools-master-images/1359208250171461632/artifacts/build-resources/pods.json
```
oc image mirror --registry-config=/etc/push-secret/.dockerconfigjson --continue-on-error=true --max-per-registry=20 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a32077727aa2ef96a1e2371dbcc53ba06f3d9727e836b72be0f0dd4513937e1e=registry.ci.openshift.org/ocp/4.7:machine-os-content
```

The source image is taken from the imagestream pipeline
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/promote-release-openshift-machine-os-content-e2e-aws-4.7/1359240250689327104/artifacts/build-resources/imagestreams.json

```
      "status": {
        "dockerImageRepository": "image-registry.openshift-image-registry.svc:5000/ci-op-9qkmyvrz/pipeline",
        "publicDockerImageRepository": "registry.build01.ci.openshift.org/ci-op-9qkmyvrz/pipeline",
        "tags": [
          {
            "tag": "machine-os-content",
            "items": [
              {
                "created": "2021-02-09T20:38:33Z",
                "dockerImageReference": "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a32077727aa2ef96a1e2371dbcc53ba06f3d9727e836b72be0f0dd4513937e1e",
                "image": "sha256:a32077727aa2ef96a1e2371dbcc53ba06f3d9727e836b72be0f0dd4513937e1e",
                "generation": 2
              }
            ]
          },
```

The previous way of getting the image spec uses `dockerImageReference` and replaces the internal registry's DNS with the public one. If there is no internal DNS, it will return as it it. This algorithm is fine when the image is built by CI-Operator:

```
      "status": {
        "dockerImageRepository": "image-registry.openshift-image-registry.svc:5000/ci-op-q1ix6b8x/pipeline",
        "publicDockerImageRepository": "registry.build02.ci.openshift.org/ci-op-q1ix6b8x/pipeline",
        "tags": [
          {
            "tag": "applyconfig",
            "items": [
              {
                "created": "2021-02-09T18:47:02Z",
                "dockerImageReference": "image-registry.openshift-image-registry.svc:5000/ci-op-q1ix6b8x/pipeline@sha256:d210308d3b5b9396167c1b11ab27816e8ce726d7120b9455c2af1fea4f98073b",
                "image": "sha256:d210308d3b5b9396167c1b11ab27816e8ce726d7120b9455c2af1fea4f98073b",
                "generation": 6
              }
            ]
          },
```

The source will be `registry.build02.ci.openshift.org/ci-op-q1ix6b8x/pipelinepipeline@sha256:d210308d3b5b9396167c1b11ab27816e8ce726d7120b9455c2af1fea4f98073b`.

However, in the failed job, the source is `quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a32077727aa2ef96a1e2371dbcc53ba06f3d9727e836b72be0f0dd4513937e1e`. Mirror failed because there is no pull secret in /etc/push-secret/.dockerconfigjson for `quay.io/openshift-release-dev`.

The new algorithm will use (`publicDockerImageRepository@item[0].image`) `registry.build02.ci.openshift.org/ci-op-q1ix6b8x/pipeline@sha256:d210308d3b5b9396167c1b11ab27816e8ce726d7120b9455c2af1fea4f98073b` as source instead.


@smarterclayton 
- Can we also resolve the issue by adding the pull secret for quay?
- How the image from quay was imported in the first place?

**Comment by smarterclayton** [comment]
> Can we also resolve the issue by adding the pull secret for quay?

Yes that is a workaround, BUT

The point of openshift image streams and the registry is to make moving images around easy.  So image streams are like a handy coat hanger - import an image to your house, then you can move the coat (the image) around from hanger to hanger easily.  Image streams come with caching advantages and security advantages.  When you use the dockerImageReference directly you are sending the client tools to the upstream vs to your local cache.  So we use image streams directly to make local images efficient and resilient.  When we promote we're mirroring from our current location (the image we concretely know) to a remote location.  It's possible in some scenarios that we're sourcing that image from a place where the image might not exist after the test runs, and if you mirror by looking at dockerImageReference that isn't fully correct.

So in general, when you're tagging images into streams, moving them around on a cluster, you want to reference them locally.  If you're in a pod on that cluster, accessing the image registry directly is super efficient, and the mirror command is then copying locally to the target promotion location, not copying from one remote source to another (which is less efficient).

**Comment by stevekuznetsov** [comment]
Uh - why is this necessary? We should configure the ImageStream spec to honor the correct references.

```
$ oc explain imagestreamtag.tag.referencePolicy
KIND:     ImageStreamTag
VERSION:  image.openshift.io/v1

RESOURCE: referencePolicy <Object>

DESCRIPTION:
     ReferencePolicy defines how other components should consume the image.

     TagReferencePolicy describes how pull-specs for images in this image stream
     tag are generated when image change triggers in deployment configs or
     builds are resolved. This allows the image stream author to control how
     images are accessed.

FIELDS:
   type	<string> -required-
     Type determines how the image pull spec should be transformed when the
     image stream tag is used in deployment config triggers or new builds. The
     default value is `Source`, indicating the original location of the image
     should be used (if imported). The user may also specify `Local`, indicating
     that the pull spec should point to the integrated container image registry
     and leverage the registry's ability to proxy the pull to an upstream
     registry. `Local` allows the credentials used to pull this image to be
     managed from the image stream's namespace, so others on the platform can
     access a remote image but have no access to the remote secret. It also
     allows the image layers to be mirrored into the local registry which the
     images can still be pulled even if the upstream registry is unavailable.
```

Set to `Local`

**Comment by hongkailiu** [comment]
/close

Will reopen if needed.
Discussed with Steve on https://github.com/openshift/ci-tools/pull/1680#issuecomment-777851801
And we agreed on <publicDockerImageRepository>@digest

**Pull request closed without merging**
