### PR TITLE
cmd/ocp-build-data-enforcer: Fix "to mach" -> "to match" typo

### PR DESCRIPTION
**Pull request by wking**
Typo from fe83470357 (#1106).

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Included in https://github.com/openshift/ci-tools/pull/1156
/cose

**Comment by wking** [comment]
Re-opened and rebased onto master, because #1156 ended up getting closed.

**Comment by alvaroaleman** [comment]
Good point. However we need to make sure that all currently open PRs are closed before we merge this, because we match by title and if we change the title, we won't match anymore.
/hold

**Comment by wking** [comment]
I  went ahead and closed openshift/cluster-version-operator#456, so we're ready for the replacement  ;).

**Comment by alvaroaleman** [comment]
> I went ahead and closed openshift/cluster-version-operator#456, so we're ready for the replacement ;).

Not really: https://github.com/search?q=is%3Apr+author%3Aopenshift-bot+is%3Aopen+baseimage&type=Issues&pr=true

**Comment by wking** [comment]
Yeah, I'll let other teams merge or close as they see fit.  Using the mass commenter would allow DPTP to mass-close if you want, but I'm not in a hurry here.

**Comment by wking** [comment]
Rebased again with 947413dd5 -> 7c1349311.  [Query][1] shows openshift/cluster-resource-override-admission-operator#37 as the only remaining PR from the last series.  Doesn't seem that disruptive to land this PR, close that one, and have it replaced without the typo.  Or maybe the outstanding typo will land before the next series...

[1]: https://github.com/search?q=is%3Apr+author%3Aopenshift-bot+is%3Aopen+baseimage&type=Issues&pr=true

**Review by petr-muller — APPROVED** [review]
1 PR sounds manageable to me.

/hold

**Comment by petr-muller** [comment]
Merge, wait for new image, retitle the PR should do the trick.

**Pull request merged**
