### PR TITLE
webreg: support variant jobs in the job list and search

### PR DESCRIPTION
**Pull request by AlexNPavel**
This PR adds support for displaying variant tests in the job list and search pages separately from the standard tests and providing proper hyperlinks to the the individual job pages for variant jobs.

### CODE REVIEW

**Comment by AlexNPavel** [comment]
Running example of bug and fix:

Current job page for the `openshift-release-master-{ocp-4.4,ocp-4.5}-e2e-metal-ipi-ipv4` tests: https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/search?job=ipv4

Fixed version: https://server-ci-tools-865.apps.ci.l2s4.p1.openshiftapps.com/search?job=ipv4

**Comment by stevekuznetsov** [comment]
Why not another column>

**Comment by AlexNPavel** [comment]
> Why not another column?

I don't feel like it makes sense to add a column for variant when it isn't commonly used. It would just be an empty space for the vast majority of jobs. Maybe separating variants as separate rows would be clearer though?

**Comment by stevekuznetsov** [comment]
Hm. Conceptually it should be another column, though, since it's just another identifier that can be paired with the previous three. I agree in the non-filtered overview, it would add some white-space, but as soon as someone actually searches for something we could add it or not depending on whether we need it for rendering, and it should be a non-issue?

**Comment by AlexNPavel** [comment]
> Hm. Conceptually it should be another column, though, since it's just another identifier that can be paired with the previous three. I agree in the non-filtered overview, it would add some white-space, but as soon as someone actually searches for something we could add it or not depending on whether we need it for rendering, and it should be a non-issue?

It's possible to do that, but adds a lot of complexity. I'll work on adding support and see how that goes

**Comment by AlexNPavel** [comment]
Updated to have separate column for `Variant`. Extra `Variant` column appears only when at least 1 job in the list contains a variant.

**Pull request merged**
