### PR TITLE
Split testgrid-config-generator main function

### PR DESCRIPTION
**Pull request by YuviGold**
Split main function into 3 functions:
- `findReleaseControllerJobs`
- `findAllowListJobs`
- `updateDashboards`

The `updateDashboards` goes over given periodic jobs and for each runs
`getDashboard` function that calls `getDashboardType`.

### CODE REVIEW

**Comment by YuviGold** [comment]
Bump

This PR would allow extending the current `testgrid-config-generator` functionality easily.

Please review
/cc @stevekuznetsov 
/cc @alvaroaleman
/cc @petr-muller

**Comment by petr-muller** [comment]
/uncc 

I'm not in `OWNERS` of that program and I'm not familiar with it

**Pull request closed without merging**
