### PR TITLE
rename regcred secret to registry-pull-credentials

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/openshift-team-developer-productivity-test-platform 

/hold This PR needs the corresponding changes in `openshift/release` 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

I would expect the following sequence:

1. A openshift/release PR to make our tools ensure this secret exists everywhere and has correct content, then see that the secret was correctly created everywhere (by a postsubmit)
2. Change in ci-tools to point the job to the new secret
3. openshift/release PR to regenerate all jobs
4. Last, another openshift/release PR to remove the old secrets

This PR looks like a 2) and https://github.com/openshift/release/pull/12069/ looks like a 3). Where's 1) ?

**Comment by droslean** [comment]
https://github.com/openshift/release/pull/12074 will make sure that the secret will be generated. I will update openshift/release#12069  to include only the job changes.

**Comment by droslean** [comment]
1) https://github.com/openshift/release/pull/12074 makes sure that the secret will be managed by our automation. See: [job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-release-master-build02-apply/1308308733259943936#1:build-log.txt%3A105)
2) this PR
3) https://github.com/openshift/release/pull/12069 (Changes only the jobs that are being managed by prowgen)

**Review by petr-muller — APPROVED** [review]
```console
$ for cluster in api.ci build01 build02
      oc --context $cluster get secret --namespace ci registry-pull-credentials  -o json | jq '.data[".dockerconfigjson"]' -r > rpc
      oc --context $cluster get secret --namespace ci regcred  -o json | jq '.data[".dockerconfigjson"]' -r > regcred
      diff -u rpc regcred || echo "NOOOO"
  end
```

is good so this PR should be good to go now.

**Pull request merged**
