### PR TITLE
Add hack/migrate_jobs.py

### PR DESCRIPTION
**Pull request by hongkailiu**
Solve item A in https://issues.redhat.com/browse/DPTP-704?focusedCommentId=13939017&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13939017

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
Should migrate the job even if it is not a `ci-operator` job.

```bash
(p3env) ➜  ci-tools git:(mig_jobs) release_repo=/Users/hongkliu/repo/openshift/release bash -c 'find ${release_repo}  -name "*openshift-installer-master-presubmits.yaml" -exec python3 hack/migrate_jobs.py {} \;'
WARNING:root:ignoring job pull-ci-openshift-installer-shellcheck whose image quay.io/coreos/shellcheck-alpine:v0.5.0 is not ci-operator:latest
WARNING:root:ignoring job pull-ci-openshift-installer-tf-fmt whose image quay.io/coreos/terraform-alpine:v0.12.0-rc1 is not ci-operator:latest
WARNING:root:ignoring job pull-ci-openshift-installer-tf-lint whose image quay.io/coreos/tflint is not ci-operator:latest
WARNING:root:ignoring job pull-ci-openshift-installer-yaml-lint whose image quay.io/coreos/yamllint is not ci-operator:latest

```

**Comment by stevekuznetsov** [comment]
Yes, we should migrate those jobs as well and if they're not running ci-operator it should be even easier to migrate.

**Comment by hongkailiu** [comment]
> Yes, we should migrate those jobs as well and if they're not running ci-operator it should be even easier to migrate.

Ack. They will be migrated (i.e., with `cluster` in the job def.), but they wont be provided pull-secret file and so-on (since they are for `ci-operator` to use).

**Comment by hongkailiu** [comment]
/close

merge to https://github.com/openshift/ci-tools/pull/341

**Pull request closed without merging**
