### PR TITLE
Bugzilla Backporter: Add PR status to clones table

### PR DESCRIPTION
**Pull request by GeoBK**

### CODE REVIEW

**Comment by GeoBK** [comment]
cc @alvaroaleman

**Comment by alvaroaleman** [comment]
This depends on bumping test-infra so
/hold

**Comment by stevekuznetsov** [comment]
What's the context for this? This PR is not reviewable by itself.

**Comment by GeoBK** [comment]
This PR is supposed to add the PR status to the clones table in the backporter tool.
This is accompanied by [this](https://github.com/kubernetes/test-infra/pull/18953) change in test-infra. 
image

**Comment by stevekuznetsov** [comment]
Instead of adding the word to the end of the cell can we add the GitHub icon for open/closed/merged to the start of the link?

**Comment by stevekuznetsov** [comment]
Looks like GitHub does with CSS?

```
<svg class="octicon octicon-git-merge" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M5 3.254V3.25v.005a.75.75 0 110-.005v.004zm.45 1.9a2.25 2.25 0 10-1.95.218v5.256a2.25 2.25 0 101.5 0V7.123A5.735 5.735 0 009.25 9h1.378a2.251 2.251 0 100-1.5H9.25a4.25 4.25 0 01-3.8-2.346zM12.75 9a.75.75 0 100-1.5.75.75 0 000 1.5zm-8.5 4.5a.75.75 0 100-1.5.75.75 0 000 1.5z"></path></svg>
```

**Comment by GeoBK** [comment]
This is what it looks like now. But I feel the text would be more understandable (depending on who the users are).
I have added a tooltip to help with that in either case.
image

**Comment by GeoBK** [comment]
The status returned by the /rest/api include external bugs is not what is expected so putting this on hold until there is a resolution for [https://bugzilla.redhat.com/show_bug.cgi?id=1872808](this)

**Pull request closed without merging**
