### PR TITLE
Mark RPM_REPO_OPENSHIFT_ORIGIN as calculated at test time (for v3.11)

### PR DESCRIPTION
**Pull request by DennisPeriquet**
For the new e2e-aws job I'm introducing in [release/PR26155](https://github.com/openshift/release/pull/26155), I need to make the change in this PR so that I can define a different `RPM_REPO_OPENSHIFT_ORIGIN` containing rpms built by the CI test.

I make the change so that it's very Openshift 3.11 specific and won't disturb anything related to 4.x or any existing 3.11 tests that use this template.

Even if this PR were to merge, nothing new would happen -- except PR26155 above would pass CI when prowgen is run.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Every test has environment variables with the organization, repository, branch, and job name:

- https://docs.ci.openshift.org/docs/architecture/step-registry/#available-environment-variables
- https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables

Wouldn't it be simpler to add these checks there?

**Comment by DennisPeriquet** [comment]
@bbguimaraes thanks for the links.  But I don't see how those variables will help.

My [PR26155](https://github.com/openshift/release/pull/26155), won't pass CI in the openshift/release repo because when prowgen runs (the file I'm modifying in this PR is part of prowgen), prowgen will not add in the `RPM_REPO_OPENSHIFT_ORIGIN` variable.

`RPM_REPO_OPENSHIFT_ORIGIN` is needed by the new e2e-aws test in the generated jobs file (it is a required variable) and it needs to be something other than the default value used so that I can tell that it's for the new e2e-aws test.

I manually added the value in the jobs file that prowgen generated for PR26155 to ensure that the new e2e-aws test is working, runs, and passes but that variable needs to be added by prowgen so that CI in openshift/release repo will pass.

**Comment by bbguimaraes** [comment]
What you want (RPMs built by `ci-operator`) should already be done, that is why this exception exists in `prowgen`.  See for example the GCP job, which does not declare the variable but gets it from `ci-operator`:

- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/26898/pull-ci-openshift-origin-release-3.11-e2e-gcp/1515874620010401792#1:build-log.txt%3A19
- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/26898/pull-ci-openshift-origin-release-3.11-e2e-gcp/1515874620010401792/artifacts/build-resources/pods.json

Which configuration did you try which did not get `RPM_REPO_OPENSHIFT_ORIGIN`?  That would be an error in `ci-operator`.

**Comment by DennisPeriquet** [comment]
@bbguimaraes that's interesting.  When I ran that e2e-gcp test in [PR26155](https://github.com/openshift/release/pull/26155), I printed out `RPM_REPO_OPENSHIFT_ORIGIN` and the value was https://artifacts-rpms-openshift-origin-ci-rpms.apps.ci.l2s4.p1.openshiftapps.com/openshift-origin-v3.11/.  So I guess that's just not used in e2e-gcp.  But I'm using a different [template](https://github.com/openshift/release/blob/e36ac0af38acbffe8dab7829d95332a15b0f5ea9/ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-ansible.yaml) for my new e2e-aws in PR26155.

That template requires `RPM_REPO_OPENSHIFT_ORIGIN` and it's not there for the new e2e-aws test which is why I created this PR.

**Comment by bbguimaraes** [comment]
> @bbguimaraes that's interesting. When I ran that e2e-gcp test in [PR26155](https://github.com/openshift/release/pull/26155), I printed out `RPM_REPO_OPENSHIFT_ORIGIN` and the value was `https://artifacts-rpms-openshift-origin-ci-rpms.apps.ci.l2s4.p1.openshiftapps.com/openshift-origin-v3.11/`. Here's a [run](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26155/rehearse-26155-pull-ci-openshift-image-registry-release-3.11-e2e-gcp/1516198488507944960/artifacts/build-resources/pods.json) but I realize the git ahsh for that is probably gone from a git squash.

That's because the variable is manually set in that job:

- https://github.com/openshift/release/blob/12ce13ee31239600c7fb3503c3e68b270eb146bd/ci-operator/jobs/openshift/image-registry/openshift-image-registry-release-3.11-presubmits.yaml#L34-L35
- https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/26155/rehearse-26155-pull-ci-openshift-image-registry-release-3.11-e2e-gcp/1516198488507944960/podinfo.json

The way this is supposed to work is:

- For `openshift/origin` tests, we want the CI version of the repository which was just built for the PR.  This is the default mode of operation for `ci-operator`, so `prowgen` generates a regular job.
- For other repositories, we want the tests to use an existing repository (not built in the test namespace, since they don't build `openshift/origin`), so `prowgen` adds the `RPM_REPO_OPENSHIFT_ORIGIN` variable pointing to the `app.ci` URL.

In both cases, `RPM_REPO_OPENSHIFT_ORIGIN` will be set: implicitly by `ci-operator` in the first, explicitly by `prowgen` in the second.  If it's not, that is a problem in `ci-operator` and should be fixed.

**Comment by DennisPeriquet** [comment]
@bbguimaraes thanks for the comment! and sorry for my delay in replying (I was on TRT watch this week).  I hope to get back to this soon.

I'm going to look in this repo for all the places `RPM_REPO_OPENSHIFT_ORIGIN` occurs and see if I can figure out where ci-operator is going wrong.

Thanks again.

**Pull request closed without merging**
