### PR TITLE
 ci-operator: initialize a lease client only when appropriate

### PR DESCRIPTION
**Pull request by stevekuznetsov**
/assign @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by alvaroaleman** [comment]
hold

**Comment by stevekuznetsov** [comment]
```
 error: could not run steps: step e2e-aws-upgrade failed: step needs a lease but no lease client provided 
```

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_ci-tools/733/pull-ci-openshift-ci-tools-master-integration/2415#1:build-log.txt%3A81

WTF

**Comment by stevekuznetsov** [comment]
OK, it was just a bug in our integration tests

**Pull request merged**
