### PR TITLE
`pod-scaler`: modify pruning logic to only keep 25 fingerprints

### PR DESCRIPTION
**Pull request by smg247**
The data we have stored for `pod-scaler` is getting out of control. It has more than doubled in size in the last year. The memory consumption for the UI is nearly 30GB, and it is largely due to how much data it has to process. Let's cut this down to only 25 fingerprints per histogram.

For: https://issues.redhat.com/browse/DPTP-3288

/cc @bbguimaraes @danilo-gemoli

### CODE REVIEW

**Review by droslean — APPROVED** [review]

**Comment by bbguimaraes** [comment]
Since data are written to disk after being processed, shouldn't we see memory usage reduced to almost nothing (following CPU usage) if it is caused by the processing of the input?

2023-01-30-165010_1920x2160_scrot
2023-01-30-165013_1920x2160_scrot

Also, the maximum size of the input is below 1GB (and is around 2GB in total), I wonder what we do that requires ~15x that much to process:

```console
$ gsutil ls -lh gs://origin-ci-resource-usage-data/*
gs://origin-ci-resource-usage-data/pods/:
111.87 MiB  2023-01-30T15:06:52Z  gs://origin-ci-resource-usage-data/pods/container_cpu_usage_seconds_total.json
195.79 MiB  2023-01-30T15:06:35Z  gs://origin-ci-resource-usage-data/pods/container_memory_working_set_bytes.json
                                                                    
gs://origin-ci-resource-usage-data/prowjobs/:
225.62 MiB  2023-01-30T15:05:32Z  gs://origin-ci-resource-usage-data/prowjobs/container_cpu_usage_seconds_total.json
214.72 MiB  2023-01-30T15:06:05Z  gs://origin-ci-resource-usage-data/prowjobs/container_memory_working_set_bytes.json
                                                                    
gs://origin-ci-resource-usage-data/steps/:        
512.44 MiB  2023-01-30T15:08:19Z  gs://origin-ci-resource-usage-data/steps/container_cpu_usage_seconds_total.json
864.76 MiB  2023-01-30T15:10:24Z  gs://origin-ci-resource-usage-data/steps/container_memory_working_set_bytes.json
TOTAL: 6 objects, 2228435677 bytes (2.08 GiB)
```

Reducing the input by half should help, of course, but there seems to be more involved than that.

**Comment by smg247** [comment]
@bbguimaraes It appears that once the pod-scaler-ui processes the data, it stores the mappings and indices in memory. https://github.com/openshift/ci-tools/blob/35256a630098713fb2647b69dba6b385f8604271/cmd/pod-scaler/frontend.go#L318-L322

Perhaps that is what creates this footprint?

My findings, including a pprof analysis, are in the comments on: https://issues.redhat.com/browse/DPTP-3288. This is intended to be a first pass though, we can do a deeper analysis if needed after we see the results here.

**Comment by smg247** [comment]
@droslean, I had to fix some whitespace changes that my IDE made for me in the expected results of the e2e test. Can you tag this again?

**Pull request merged**
