### PR TITLE
Migrate rpm server to python3

### PR DESCRIPTION
**Pull request by tnozicka**
After switching to ubi8 we got python3 which borked the rpm serving job.
```
error: some steps failed:
  * could not run steps: step [serve:rpms] failed: could not wait for RPM repo server to deploy: could not wait for deployment: could not determine current deployment status: the deployment config ci-op-n0mp9vmb/rpm-repo failed with status "ProgressDeadlineExceeded"
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/350/pull-ci-openshift-kubernetes-master-images/1305758717110652928#1:build-log.txt%3A73

logs showed
```
Traceback (most recent call last):
  File "/tmp/tmp.p6rDk9qoF9", line 1, in <module>
    import time, threading, socket, socketserver, BaseHTTPServer, SimpleHTTPServer
ModuleNotFoundError: No module named 'BaseHTTPServer'
```

This switches the python code to python3 to get us unstuck.

/cc @soltysh @marun @stevekuznetsov @petr-muller

### CODE REVIEW

**Comment by tnozicka** [comment]
fyi, this is blocking every merge to openshift/kubernetes and blocking delivering 4.6.0 fixes

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
