### PR TITLE
Fix some snyk code issues

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2899

The PR fixed all [high] and some [medium] issues.

The left ones are all

```
[Medium] Clear Text Logging
```

I have no idea how to fix them.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Although there are some actual problems being corrected, a lot of this is quite silly (the "vulnerabilities", not the work).  MD5 is perfectly fine for what we are doing, Github has a strict policy for user names ("[u]sername may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen"), etc.

The first commit is a bit messy, can you take the renames out of it?

Can we even make the `prpq_reconciller` change while maintaining compatibility with the existing data?

/hold

**Comment by hongkailiu** [comment]
> a lot of this is quite silly (the "vulnerabilities", not the work)

Thanks for the review.
I spent too much time on those silly things.

Let us hold it until we are sure about using synk at all.
If we still want it, then I will address your comments.

**Comment by jmguzik** [comment]
@hongkailiu I think it is resolved elsewhere and you can close

**Comment by hongkailiu** [comment]
Seem that we do not care about it any more.

**Pull request closed without merging**
