### PR TITLE
Update test-infra to c1043ab1c1ff

### PR DESCRIPTION
**Pull request by alvaroaleman**

### CODE REVIEW

**Comment by alvaroaleman** [comment]
/hold
until dependant bumps merge

**Comment by alvaroaleman** [comment]
/hold
failure appears genuine

**Comment by alvaroaleman** [comment]
Requires:
* https://github.com/openshift/ci-chat-bot/pull/203
* https://github.com/openshift/release-controller/pull/309

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
