### PR TITLE
prowgen: duplicate tests on build01 that don't use quota

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @hongkailiu @petr-muller

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Integration is stuck on 

```
[INFO] Running `secret-wrapper sleep 1d` and sending SIGINT...
```

cc @bbguimaraes

**Comment by stevekuznetsov** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_ci-tools/525/pull-ci-openshift-ci-tools-master-integration/1793

/test integration

**Comment by bbguimaraes** [comment]
@stevekuznetsov: I also saw a failure in that area yesterday (although that test has a very short timeout, was it really stuck?), it was because the test was starved.

**Pull request merged**
