### PR TITLE
vsphere - remove unused cluster profiles

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/hold for 
https://github.com/openshift/release/pull/54779

**Comment by jcpowermac** [comment]
@psalajova @danilo-gemoli any idea why e2e keeps failing? Not seeing anything related to this PR

**Comment by psalajova** [comment]
@jcpowermac I have no idea why the tests are failing, it's a simple change... maybe try to rebase and push the changes again?

**Pull request merged**
