### PR TITLE
pkg/defaults: add step leases to tests

### PR DESCRIPTION
**Pull request by bbguimaraes**
Includes https://github.com/openshift/ci-tools/pull/1455.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
https://issues.redhat.com/browse/DPTP-1365

**Review by stevekuznetsov — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
Updated this with:

```
git fetch upstream master
git fetch upstream pull/1456/head:bbguimaraes/lease_ref
git rebase --onto master 9527eee082ef61a13273d002127d7d2ca99197bf bbguimaraes/lease_ref
git push git@github.com:bbguimaraes/ci-tools.git bbguimaraes/lease_ref:lease_ref --force
```

**Pull request merged**
