### PR TITLE
Vault secret collection manager: Add edit members functionality

### PR DESCRIPTION
**Pull request by alvaroaleman**
Ref https://issues.redhat.com/browse/DPTP-1891

/label tide/merge-method-squash

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Preview is at https://vault-secret-collection-manager-ci-tools-1772.apps.ci.l2s4.p1.openshiftapps.com

**Comment by stevekuznetsov** [comment]
How easy would it be to switch the two columns in the UI? In my experience it's most common to have the flow be from left to right, so the right side is the list of members and you pull people into or out of the right side

**Review by stevekuznetsov — APPROVED** [review]
Testing the UI out looks good
/hold

**Comment by alvaroaleman** [comment]
>  How easy would it be to switch the two columns in the UI? In my experience it's most common to have the flow be from left to right, so the right side is the list of members and you pull people into or out of the right side

Updated, however I think it is no difference in term of untuitivity because one of "Add a new member" and "Remove an existing member" will always be from right to left and thus unintuitive.

**Pull request merged**
