### PR TITLE
vendor: bump k8s.io/test-infra

### PR DESCRIPTION
**Pull request by stevekuznetsov**
We need this to handle the new config fields for [DPTP-1962](https://issues.redhat.com/browse/DPTP-1962)

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Good lord why on _earth_ did we duplicate the censoring tests from upstream here. We've duplicated them _three times_ by my count. You don't need to write unit tests to test that an upstream library does the right thing when the library has literally the same tests. It's insanity.

**Comment by petr-muller** [comment]
LGTM but needs `make generate`

/retitle vendor: bump k8s.io/test-infra

**Pull request merged**
