### PR TITLE
ci-operator: expose which resource was leased to steps

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @bbgui

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
OK, updated -- did a tiny refactor ro make it easier.

**Comment by stevekuznetsov** [comment]
Hmmmm... `make update-integration` did not work as expected.

**Comment by alvaroaleman** [comment]
> Hmmmm... make update-integration did not work as expected.

So fix it :)

**Comment by stevekuznetsov** [comment]
@alvaroaleman what do you think I was doing, huh? :)

**Comment by stevekuznetsov** [comment]
WTF.

**Comment by stevekuznetsov** [comment]
NVM this should be good

**Pull request merged**
