### PR TITLE
ci-op: use group <author>-group in rolebinding/ci-op-author-access

### PR DESCRIPTION
**Pull request by hongkailiu**
The first commit reverts https://github.com/openshift/ci-tools/pull/2398/files

/cc @openshift/test-platform 

https://issues.redhat.com/browse/DPTP-1840

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold
need https://github.com/openshift/release/pull/22426

**Comment by droslean** [comment]
Looks good.
@hongkailiu  Can you make sure that the job has run and created the groups before merging this?

/lgtm

**Comment by hongkailiu** [comment]
> Looks good. @hongkailiu Can you make sure that the job has run and created the groups before merging this?
> 
> /lgtm

Sure. I will watch the groups. (i put a hold already.)

**Comment by hongkailiu** [comment]
The job is green and the groups are created on clusters.
I will cancel the hold on Monday.

**Pull request merged**
