### PR TITLE
Update to use the coreydaley/openshift-goimports repository

### PR DESCRIPTION
**Pull request by coreydaley**
Repository was moved/renamed.

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@coreydaley it seems your PR touches other dependencies. You can use the `make update-vendor` maketarget to update the vendor folder in a way that doesn't differ from what CI checks

**Comment by coreydaley** [comment]
@alvaroaleman I get the following error trying to run that command
```
build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
make: *** [Makefile:91: update-vendor] Error 1
```

**Comment by coreydaley** [comment]
I added `-e GOCACHE=/tmp/go-build-cache`  and it was able to run now.

**Review by alvaroaleman — APPROVED** [review]
/label tide/merge-method-squash

**Pull request merged**
