### PR TITLE
webreg: expose step environment variables

### PR DESCRIPTION
**Pull request by petr-muller**
Add a new "Environment" section to the step page, containing a table
with different elements that expose something to the step payload as
an environmental variable:

- dependencies
- parameters
- leases

Example deployment: https://server-ci-tools-1568.apps.ci.l2s4.p1.openshiftapps.com/

Part of [DPTP-1652](https://issues.redhat.com/browse/DPTP-1652)

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Can you deploy an example?

**Comment by petr-muller** [comment]
Oh yeah, got distracted by the lint failure:

https://server-ci-tools-1568.apps.ci.l2s4.p1.openshiftapps.com/

**Comment by petr-muller** [comment]
This is a good testcase: https://server-ci-tools-1568.apps.ci.l2s4.p1.openshiftapps.com/reference/openshift-e2e-test

**Comment by stevekuznetsov** [comment]
Love that.

**Review by stevekuznetsov — APPROVED** [review]

**Review by alvaroaleman — APPROVED** [review]

**Comment by petr-muller** [comment]
That last push was a mistake :/

**Pull request merged**
