### PR TITLE
Rename filename cluster-init.yaml

### PR DESCRIPTION
**Pull request by hongkailiu**
The yaml files in the folder are usually manifests for the clusters and are applied by `applyconfig`.
This file is a config file for the tool.
Let us ignore it by `_` prefix in the name.

/cc @openshift/test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
/hold

need to go together with https://github.com/openshift/release/pull/25221

**Review by petr-muller — APPROVED** [review]

**Comment by hongkailiu** [comment]
> Huh does this mean that `applyconfig` currently tries to `oc apply` it? Why isn't it failing?

No. Its parent folder is not used as an arg for `applyconfig`. We use its subfolders `build0n` instead.
But for sync-rover-groups, I will use its parent folder.
https://github.com/openshift/ci-tools/pull/2595

**Pull request merged**
