### PR TITLE
create QE dedicated azure cluster profiles

### PR DESCRIPTION
**Pull request by jianlinliu**
After discuss with DPP and Installer dev team, QE should use our dedicated cluster profiles.

### CODE REVIEW

**Comment by jianlinliu** [comment]
cc @yunjiang29 @Amoghrd to be noticed and review.

**Comment by yunjiang29** [comment]
looks like the content in `pkg/prowgen/prowgen.go` has been moved to `pkg/prowgen/podspec.go` https://github.com/openshift/ci-tools/pull/2284

**Comment by yunjiang29** [comment]
looks like the content in `pkg/prowgen/prowgen.go` has been moved to `pkg/prowgen/podspec.go` https://github.com/openshift/ci-tools/pull/2284

**Comment by jianlinliu** [comment]
@hongkailiu or @jmguzik can you help review and merge it.

**Review by droslean — APPROVED** [review]

**Pull request merged**
