### PR TITLE
test: add an e2e test that runs simple commands

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Biggest question is ... will we have the RBAC we need?

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
OK, cool. The job fails as expected. The `default` service account in the namespace is not the `ci-operator` service account we usually run the jobs with, so the job itself cannot do `ci-operator` inception. @bbguimaraes @petr-muller do you think there are any sensible options for how to give the correct credentials to this test without the credential proposal?

**Comment by petr-muller** [comment]
> do you think there are any sensible options for how to give the correct credentials to this test without the credential proposal?

Well the credential proposal only gives the multi-stage tests the ability to receive a secret from the `ci` namespace - for container-based tests we can to it even today with [`tests.secrets`](https://github.com/openshift/ci-tools/blob/master/CONFIGURATION.md#testssecrets). So if we can pass sufficient credentials to the test to be able to run ci-operator, we should be able to do that even today.

**Comment by stevekuznetsov** [comment]
@petr-muller interesting.

**Pull request merged**
