### PR TITLE
Stop setting redundant flags

### PR DESCRIPTION
**Pull request by hongkailiu**
Required by https://github.com/openshift/release/pull/5171

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
> We could do this but I was hoping to centralize this logic upstream so we don't copy it in every binary :)

Do you mean when NewGithubClient ... and the client does the init and save the user data as a field?

**Comment by stevekuznetsov** [comment]
Yes. I'm working on it, you don't need to worry about it for now.

**Comment by hongkailiu** [comment]
> Yes. I'm working on it, you don't need to worry about it for now.

ACK.

**Pull request closed without merging**
