### PR TITLE
make: add simple targets to streamline e2e

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @alvaroaleman

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Nice, I've been meaning to add something similar.  It would be good to follow the `$TMPDIR` convetion and to place the files under a sub-directory:

```make
TMPDIR ?= /tmp

$(TMPDIR)/ci-tools/e2e: # bikeshed
	mkdir -p $@
```

**Comment by stevekuznetsov** [comment]
@bbguimaraes updated to use `$(TMPDIR)`

**Pull request merged**
