### PR TITLE
Update test-infra

### PR DESCRIPTION
**Pull request by 2uasimojo**
...particularly to pick up https://github.com/kubernetes/test-infra/pull/22502 (`skip_if_only_changed` prow job option)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/hold

The following must merge first:
- https://github.com/openshift/release-controller/pull/280
- https://github.com/openshift/ci-chat-bot/pull/175

Then I'll need to update this repo's vendored deps of the above.

**Comment by 2uasimojo** [comment]
> /retest

@alvaroaleman still [waiting on deps](https://github.com/openshift/ci-tools/pull/2068#issuecomment-862513969)

**Comment by 2uasimojo** [comment]
/retest

/hold cancel

Deps have merged.

**Comment by 2uasimojo** [comment]
> Then I'll need to update this repo's vendored deps of the above.

I guess those aren't vendored here; just transitive/dynamic.

**Comment by alvaroaleman** [comment]
@2uasimojo you need to run `make update-integration`

**Comment by 2uasimojo** [comment]
> @2uasimojo you need to run `make update-integration`

Roger that.

And to do so, apparently I need to `make build` first (`entrypoint-wrapper` 404).

Thanks.

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
