### PR TITLE
Increase timeout when trying to create rbacs.

### PR DESCRIPTION
**Pull request by droslean**
/cc @openshift/openshift-team-developer-productivity-test-platform 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@droslean this takes more than five mintes? Can you create a BZ? That is definitely not supposed to take this long.

**Comment by droslean** [comment]
@alvaroaleman The main problem is that the dockercfgcontroller doesn't leave any annotation with information of when it actually synced the service account. I will open a BZ to see if there is any workaround to get this info or implement this. In the meanwhile, I would like to increase the timeout and monitor the jobs to see if we still hit the error.

**Comment by alvaroaleman** [comment]
> The main problem is that the dockercfgcontroller doesn't leave any annotation with information of when it actually synced the service account

Why would we need an annotation? Our success check is `if len(actualSA.ImagePullSecrets) > 0`. A controller that needs more than five minutes for syncing some data in the same cluster is absolutely not expected and if it indeed takes so long, that is a bug in that controller (probably too little workers).

**Comment by droslean** [comment]
@alvaroaleman We don't need annotation here. I need the annotation to figure out if the problem if there is a problem with the controller at all. Now we are blind.

**Comment by alvaroaleman** [comment]
@droslean can you please just create a BZ instead and link to that BZ from the code, together with sample jobs where the 5 min timeout wasn't enough? If this happens its a product bug and the responsible team needs to debug and fix it.

**Pull request closed without merging**
