### PR TITLE
Bump test-infra to f8dbf1fd3d25

### PR DESCRIPTION
**Pull request by alvaroaleman**
Needed to be able to use https://github.com/kubernetes/test-infra/pull/22886
/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by alvaroaleman** [comment]
Needs
* https://github.com/openshift/ci-chat-bot/pull/186
* https://github.com/openshift/release-controller/pull/289

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
