### PR TITLE
DPTP-3826: Adding ODF cluster profile

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Added a new cluster profile to be used for ODF, i.e, projects under `red-hat-storage` org.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
cc @malayparida2000 @iamniting

**Comment by malayparida2000** [comment]
Looking at https://github.com/openshift/ci-tools/pull/1548/files & https://github.com/openshift/ci-tools/pull/1818/files, don't we need to make changes at other places also as made in these 2 similar PRs?

**Comment by Nikhil-Ladha** [comment]
> Looking at #1548 & #1818, don't we need to make changes at other places like inside the prowgen folder also as made in these 2 similar PRs?

Those are very old PRs, I think the latest way to add profiles have been updated a bit and even the [example](https://github.com/openshift/ci-tools/pull/2808) PR given in the docs just mentions updating the `types.go` file.

**Comment by malayparida2000** [comment]
Hm, I see they have moved around those functions so those changes might not be necessary anymore.

**Comment by Nikhil-Ladha** [comment]
@jmguzik @droslean @psalajova can you please review the PR and approve if all looks good? So, that we can move ahead with making other required changes?

**Pull request closed without merging**
