### PR TITLE
Fix integration test "clusterimageset-updater":  releases 4.5.* EOL

### PR DESCRIPTION
**Pull request by danilo-gemoli**
Releases `4.5.*` hit EOL and then they are no longer available:
```
time="2022-12-14T13:32:08Z" level=info msg="Requesting a release from https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4-stable/latest?in=%3E4.5.0-0+%3C4.6.0-0"
time="2022-12-14T13:32:08Z" level=fatal msg="Failed to get pullspec for version range `>4.5.0-0 <4.6.0-0`" error="failed to request latest release: server responded with 404: no tags exist within the release that satisfy the request\n"
```
this is causing the integration test `make integration SUITE=clusterimageset-updater` to miserably fail.

### CODE REVIEW

**Comment by danilo-gemoli** [comment]
This is an expected failure that we are going to address  as soon as possible
/override ci/prow/e2e

**Review by hongkailiu — APPROVED** [review]

**Comment by danilo-gemoli** [comment]
/override ci/prow/e2e
[again](https://github.com/openshift/ci-tools/pull/3200#issuecomment-1351581458)

**Review by jmguzik — COMMENTED** [review]
I have the feeling it could be bumped more than 4.7. Probably 4.11 will be safe and we would delay potential problems in the future.

**Comment by danilo-gemoli** [comment]
I'll eventually get back on this one `e2e` is solved

**Pull request merged**
