### PR TITLE
Remove cluster field from ci-operator types

### PR DESCRIPTION
**Pull request by alvaroaleman**
This PR removes the cluster field from the CI-Operator types. It will require re-generating the configs and thus potentially break in-flight PRs to o/release.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Don't we first need a PR to `openshift/release` to remove the use of these fields?

**Comment by alvaroaleman** [comment]
> Don't we first need a PR to openshift/release to remove the use of these fields?

It will fail validation.

We could:
* Remove only the validation in a dedicated PR
* Update o/release
* Then merge this

WDYT?

**Comment by stevekuznetsov** [comment]
Yeah, I think that would be optimal. We already fall back to in-cluster clients without the `cluster` field so removing the validation, then the fields should be a no-op.

**Comment by stevekuznetsov** [comment]
I think we're ready for this now

/lgtm
/hold

**Comment by alvaroaleman** [comment]
ffs
/retest

**Pull request merged**
