### PR TITLE
Fix the line breaks of the command in promotion pod

### PR DESCRIPTION
**Pull request by hongkailiu**
/hold

will rebase after https://github.com/openshift/ci-tools/pull/1816

/cc @stevekuznetsov @alvaroaleman 

I should not have cared much about the readability of the cmd. :sigh

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by hongkailiu** [comment]
/hold

Let me do a test with the built image in ci.

**Comment by hongkailiu** [comment]
It works.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-ci-ns-ttl-controller-master-images/1375175116702355456

just in case:

```
oc get is ci-operator -n ci -o yaml | yq -y '.status.tags[]|select(.tag=="latest") | .items[0]'
created: '2021-03-25T19:31:04Z'
dockerImageReference: image-registry.openshift-image-registry.svc:5000/ci/ci-operator@sha256:a375d0a610b4d8461c65bb0951dea0da837aa47b06e11de2762d7e9a6c0d9309
generation: 489
image: sha256:a375d0a610b4d8461c65bb0951dea0da837aa47b06e11de2762d7e9a6c0d9309
```

**Pull request merged**
