### PR TITLE
Bump vendored Hive types

### PR DESCRIPTION
**Pull request by petr-muller**
Hive changed the semantics of `status.ready` which broke our balancing logic. We need to use the new `status.standby` now and for that we need the new types.

```console
$ go get -u github.com/openshift/hive/apis
$ go mod vendor
$ go mod tidy
```

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold 

Huh I get problems unless I also bump test-infra? Need to look better.

**Comment by hongkailiu** [comment]
> Huh I get problems unless I also bump test-infra? Need to look better.

AFAICT, Hive version is pretty independent of test-infra.

**Comment by hongkailiu** [comment]
https://issues.redhat.com/browse/DPTP-2720

**Comment by petr-muller** [comment]
The integration failure is legit, I need to update the fixtures

**Comment by hongkailiu** [comment]
> Yeah, it's weird. I ended up doing `go get -u github.com/openshift/hive/apis` then I reverted everythign that was not Hive.

Oh. I see.
That is what I do too upon bumping hive version.

**Review by hongkailiu — APPROVED** [review]

**Pull request merged**
