### PR TITLE
Allow README and OWNERS in registry directories

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @AlexNPavel

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/close
https://github.com/openshift/ci-tools/pull/275

**Comment by AlexNPavel** [comment]
1 issue: the registry directories that are used for the tests are in `tests/multistage-registry`. The directory you added to is the ci-operator config directories.

**Pull request merged**
