### PR TITLE
OCPQE-26170: Add cluster profiles for Azure HCP QE

### PR DESCRIPTION
**Pull request by fxierh**
Create two distinct cluster profiles: one for HA jobs and one for all other jobs.

### CODE REVIEW

**Comment by fxierh** [comment]
/cc @droslean 

Could you please take a look ? Thank you

**Comment by fxierh** [comment]
/cc @droslean 
/cc @psalajova

Could you please take a look ? Thank you

**Comment by droslean** [comment]
/close

@fxierh Please check https://github.com/openshift/release/tree/master/ci-operator/step-registry/cluster-profiles

**Comment by fxierh** [comment]
@droslean 

Thanks for the info. I've opened https://github.com/openshift/release/pull/57649, please take a look.

I followed https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/, but it seems outdated. It would be great to have it updated."

**Comment by fxierh** [comment]
/reopen

ref. https://redhat-internal.slack.com/archives/CBN38N3MW/p1728546755386689?thread_ts=1728483895.711989&cid=CBN38N3MW

**Pull request merged**
