### PR TITLE
cmd/testgrid-config-generator: Add details to the README

### PR DESCRIPTION
**Pull request by wking**
The previous invocation example was not sufficient to explain how to adjust the job labels and controller configs to acheive a particular change to the TestGrid configuration.  Hopefully the explanation I'm adding allows folks to do that without having to work through the Go source.

### CODE REVIEW

**Comment by bparees** [comment]
this looks reasonable in terms of summarizing the current state, but i would really like to see a goal state of:  testgrid dashboards are independent of release-controller behavior.  Or driven off a common set of fields.

if a job is annotated informing, it shows up in an informing dashboard
if a job is annotated blocking, it shows up in a blocking dashboard

(and ideally, those annotations also drive what shows up in release-controller)

@openshift/openshift-team-developer-productivity-test-platform

**Comment by stevekuznetsov** [comment]
@bparees not sure what you mean -- do you want to move the source of truth from a `release-controller` config into an annotation on jobs? Why is that better?

**Comment by wking** [comment]
> this looks reasonable in terms of summarizing the current state...

Can we land this as it stands then, and adjust the docs when we pivot the code?

**Comment by bparees** [comment]
can you add a step about actually committing the testgrid repo changes and submitting the PR?

**Comment by stevekuznetsov** [comment]
I was very close to automating that bit :(

**Comment by bparees** [comment]
> @bparees not sure what you mean -- do you want to move the source of truth from a release-controller config into an annotation on jobs? Why is that better?

Yes.  Because what release controller cares about and what testgrid should expose are not necessarily directly correlated and should not have to be tied together.

**Comment by wking** [comment]
> can you add a step about actually committing the testgrid repo changes and submitting the PR?

Done with d123a669 -> f53986ee.  Once @stevekuznetsov automates that, he can drop the line from the docs.

**Comment by bparees** [comment]
/lgtm

moves the ball forward, clayton and I are discussing the grander restructuring of this config/logic.

**Pull request merged**
