### PR TITLE
ci-operator: use the renamed entrypoint wrapper

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @alvaroaleman 
Part of [DPTP-1668](https://issues.redhat.com/browse/DPTP-1668)

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
ffs

**Comment by stevekuznetsov** [comment]
needs https://github.com/openshift/release/pull/16236

**Pull request merged**
