### PR TITLE
Remove aws-centos-40 cluster profile

### PR DESCRIPTION
**Pull request by psalajova**
/cc @droslean 
/hold

### CODE REVIEW

**Comment by psalajova** [comment]
@vrutkovs - Hi, you were the one who originally added this cluster profile. It is not used in any tests. We are cleaning up old unused profiles, is it ok if we remove this one or do you still need it?

**Comment by psalajova** [comment]
If this PR is merged, we should merge this one https://github.com/openshift/release/pull/52928

**Comment by vrutkovs** [comment]
Kill it
/lgtm

**Pull request merged**
