### PR TITLE
pkg/jobconfig: use generic pipeline function

### PR DESCRIPTION
**Pull request by bbguimaraes**
/hold

See https://github.com/openshift/ci-tools/pull/2628.

These may be reviewed more easily by comparing the end result to
https://github.com/openshift/ci-tools/pull/2628 as I have tried to maintain
consistency across instantiations of the pattern more than between the old and
new code (and use `--ignore-space-change`).

https://issues.redhat.com/browse/DPTP-2531

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

Seems like the original `/hold` in OP did not come through

**Comment by bbguimaraes** [comment]
- `e2e`:

```
error: unable to parse image registry.build03.ci.openshift.org/ci-op-jqcpfhh5/stable@sha256:2866ab144184e4051e5625c381919a9a7259c17dccf818e5cc76a4defaf0063e: cannot retrieve image configuration for manifest sha256:2866ab144184e4051e5625c381919a9a7259c17dccf818e5cc76a4defaf0063e: received unexpected HTTP status: 503 Slow Down
```

- `integration`: https://github.com/openshift/ci-tools/pull/2667

/retest-required

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
