### PR TITLE
Failed the build upon a file-based catalog index

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2692

/cc @openshift/test-platform @gallettilance

### CODE REVIEW

**Comment by grokspawn** [comment]
In the next 2-3 weeks, the operator-sdk team will publish a feature which might streamline this significantly.  Once pushed to master, operator-sdk will be able to handle index additions to either traditional (sqlite) or file-based catalogs, and drive the correct opm command sequences to perform the addition.  
That is, instead of doing:
- opm index add
- check for errors as a detection mechanism for FBC

you should be able to use 'operator-sdk run bundle' and the catalog type will be transparently handled for you.

**Comment by hongkailiu** [comment]
https://issues.redhat.com/browse/DPTP-2872?focusedCommentId=20298913&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20298913

/override e2e-oo

**Pull request merged**
