### PR TITLE
Autoconfigbrancher: Use UpdatePullRequestWithLabel

### PR DESCRIPTION
**Pull request by alvaroaleman**
/assign @petr-muller

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@petr-muller The test-infra update turned out to require a bit of code changes on our end, want me to move it to a dedicated PR?

**Comment by petr-muller** [comment]
@alvaroaleman it looks like the test-infra bump changed how some structs are serialized, so let's move them to a separate PR so it's easier to deal with

**Comment by alvaroaleman** [comment]
> @alvaroaleman it looks like the test-infra bump changed how some structs are serialized, so let's move them to a separate PR so it's easier to deal with

https://github.com/openshift/ci-tools/pull/475

**Comment by alvaroaleman** [comment]
@petr-muller this is passing tests now, can you have a look please?

**Pull request merged**
