### PR TITLE
[sanitize-prow-jobs] configure a different ci-operator image for the arm01 cluster in postsubmits

### PR DESCRIPTION
**Pull request by droslean**
/cc @danilo-gemoli @openshift/test-platform @aleskandro 

follow-up of https://github.com/openshift/ci-tools/pull/3613

### CODE REVIEW

**Review by aleskandro — APPROVED** [review]

**Comment by jmguzik** [comment]
what a mess

**Comment by droslean** [comment]
???

**Comment by jmguzik** [comment]
@droslean that was a comment to my bot not doing what I want :) sorry

**Pull request merged**
