### PR TITLE
Determinize job config: Set api.ci cluster if cluster is unset

### PR DESCRIPTION
**Pull request by alvaroaleman**
I do realize that mutating the jobs means the tool does more than what would expect it to do, but its the one thing we run over all jobs. Maybe rename it?

/assign @petr-muller

### CODE REVIEW

**Comment by petr-muller** [comment]
/test all

Yeah, I guess we can re-purpose this tool to "make jobs right". I'm not sure about a good name for it, though. Any ideas?

**Comment by alvaroaleman** [comment]
> Yeah, I guess we can re-purpose this tool to "make jobs right". I'm not sure about a good name for it, though. Any ideas?

What about `sanitize-prow-jobs`?

Would you be okay if I do that in follow-ups because it will be a bit fiddly to do in a way that doesn't break o/release (I guess we termporarily have to publish it under two names)?

**Comment by alvaroaleman** [comment]
/retest
works on my machine?

**Comment by alvaroaleman** [comment]
Needs https://github.com/openshift/release/pull/7815 so we actually have an `api.ci` cluster.
/hold

**Pull request merged**
