### PR TITLE
Use release controller to resolve jobs

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-2540

Will rebase after https://github.com/openshift/ci-tools/pull/2448

Require https://github.com/openshift/release-controller/pull/334

/cc @openshift/test-platform

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]
/hold

LGTM, holding to allow more reviews if needed

**Comment by petr-muller** [comment]
Bad GitHub

**Comment by hongkailiu** [comment]
This one is working too.
https://github.com/openshift/release/pull/23227#issuecomment-959022593

**Pull request merged**
