### PR TITLE
e2e: use import secrets always

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by alvaroaleman** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/1132/pull-ci-openshift-ci-tools-master-e2e/1296461674357723136#1:build-log.txt%3A56

**Comment by stevekuznetsov** [comment]
Yes, it requires https://github.com/openshift/release/pull/11130

**Comment by alvaroaleman** [comment]
Still doesn't work, but breaks on the pod itself:
```
$ k get pod -n ci-op-8lf9w1d3
NAME                                 READY   STATUS         RESTARTS   AGE
without-references-produce-content   1/2     ErrImagePull   0          31
```

```
k get imagestream -n ci-op-8lf9w1d3 -o yaml
apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    creationTimestamp: "2020-08-20T16:18:42Z"
    generation: 2
    name: pipeline
    namespace: ci-op-8lf9w1d3
    resourceVersion: "934535217"
    selfLink: /apis/image.openshift.io/v1/namespaces/ci-op-8lf9w1d3/imagestreams/pipeline
    uid: d0502e5f-e300-11ea-b8bc-42010a8e0004
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: ImageStreamImage
        name: centos@sha256:fe2347002c630d5d61bf2f28f21246ad1c21cc6fd343e70b4cf1e5102f8711a9
        namespace: openshift
      generation: 2
      importPolicy: {}
      name: os
      referencePolicy:
        type: Local
  status:
    dockerImageRepository: docker-registry.default.svc:5000/ci-op-8lf9w1d3/pipeline
    publicDockerImageRepository: registry.svc.ci.openshift.org/ci-op-8lf9w1d3/pipeline
    tags:
    - items:
      - created: "2020-08-20T16:18:42Z"
        dockerImageReference: centos@sha256:fe2347002c630d5d61bf2f28f21246ad1c21cc6fd343e70b4cf1e5102f8711a9
        generation: 2
        image: sha256:fe2347002c630d5d61bf2f28f21246ad1c21cc6fd343e70b4cf1e5102f8711a9
      tag: os
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

```
k describe pod -n ci-op-8lf9w1d3
Name:         without-references-produce-content
Namespace:    ci-op-8lf9w1d3
Priority:     0
Node:         origin-ci-ig-n-kgzv/10.142.0.17
Start Time:   Thu, 20 Aug 2020 12:18:42 -0400
Labels:       OPENSHIFT_CI=true
              build-id=0
              ci.openshift.io/multi-stage-test=without-references
              ci.openshift.io/refs.branch=master
              ci.openshift.io/refs.org=test
              ci.openshift.io/refs.repo=test
              created-by-ci=true
              job=pull-ci-test-test-master-success
Annotations:  ci-operator.openshift.io/container-sub-tests: test
              ci-operator.openshift.io/save-container-logs: true
              ci.openshift.io/job-spec:
                {"type":"presubmit","job":"pull-ci-test-test-master-success","buildid":"0","prowjobid":"uuid","refs":{"org":"test","repo":"test","base_ref...
              openshift.io/scc: restricted
Status:       Pending
IP:           172.16.136.32
IPs:          <none>
Init Containers:
  cp-secret-wrapper:
    Container ID:  docker://d8cda85c38e4a273a699c2ae8bad4c2176e6bfe0d14a82664a4e99d7558dfa5f
    Image:         registry.svc.ci.openshift.org/ci/secret-wrapper:latest
    Image ID:      docker-pullable://registry.svc.ci.openshift.org/ci/secret-wrapper@sha256:3c6c6fcf9545e70e86591fda1f1d115d763514e3493bca8e2bbd8d25e6f2abef
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
    Args:
      /bin/secret-wrapper
      /tmp/secret-wrapper/secret-wrapper
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 20 Aug 2020 12:19:03 -0400
      Finished:     Thu, 20 Aug 2020 12:19:03 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tmp/secret-wrapper from secret-wrapper (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from without-references-token-kqll2 (ro)
Containers:
  test:
    Container ID:  
    Image:         docker-registry.default.svc:5000/ci-op-8lf9w1d3/pipeline@sha256:fe2347002c630d5d61bf2f28f21246ad1c21cc6fd343e70b4cf1e5102f8711a9
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /tmp/secret-wrapper/secret-wrapper
    Args:
      /bin/bash
      -c
      #!/bin/bash
      set -eu
      echo -n "message" > ${SHARED_DIR}/file
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     100m
      memory:  200Mi
    Environment:
      BUILD_ID:       0
      CI:             true
      JOB_NAME:       pull-ci-test-test-master-success
      JOB_SPEC:       {"type":"presubmit","job":"pull-ci-test-test-master-success","buildid":"0","prowjobid":"uuid","refs":{"org":"test","repo":"test","base_ref":"master","base_sha":"6d231cc37652e85e0f0e25c21088b73d644d89ad","pulls":[{"number":1234,"author":"droslean","sha":"538680dfd2f6cff3b3506c80ca182dcb0dd22a58"}]}}
      JOB_TYPE:       presubmit
      OPENSHIFT_CI:   true
      PROW_JOB_ID:    uuid
      PULL_BASE_REF:  master
      PULL_BASE_SHA:  6d231cc37652e85e0f0e25c21088b73d644d89ad
      PULL_NUMBER:    1234
      PULL_PULL_SHA:  538680dfd2f6cff3b3506c80ca182dcb0dd22a58
      PULL_REFS:      master:6d231cc37652e85e0f0e25c21088b73d644d89ad,1234:538680dfd2f6cff3b3506c80ca182dcb0dd22a58
      REPO_NAME:      test
      REPO_OWNER:     test
      ARTIFACT_DIR:   /tmp/artifacts
      NAMESPACE:      ci-op-8lf9w1d3
      JOB_NAME_SAFE:  without-references
      JOB_NAME_HASH:  e5761
      SHARED_DIR:     /var/run/secrets/ci.openshift.io/multi-stage
    Mounts:
      /tmp/artifacts from artifacts (rw)
      /tmp/secret-wrapper from secret-wrapper (rw)
      /var/run/secrets/ci.openshift.io/multi-stage from without-references (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from without-references-token-kqll2 (ro)
  artifacts:
    Container ID:  docker://3897f647d890276f1f069e03d7b1e538f4dfef9f6fde5343324a24c3565ae26d
    Image:         busybox
    Image ID:      docker-pullable://docker.io/busybox@sha256:4f47c01fa91355af2865ac10fef5bf6ec9c7f42ad2321377c21e844427972977
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      #!/bin/sh
      set -euo pipefail
      trap 'kill $(jobs -p); exit 0' TERM
      
      touch /tmp/done
      echo "Waiting for artifacts to be extracted"
      while true; do
        if [[ ! -f /tmp/done ]]; then
          echo "Artifacts extracted, will terminate after 30s"
          sleep 30
          echo "Exiting"
          exit 0
        fi
        sleep 5 & wait
      done
      
    State:          Running
      Started:      Thu, 20 Aug 2020 12:23:36 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tmp/artifacts from artifacts (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from without-references-token-kqll2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  artifacts:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  secret-wrapper:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  without-references:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  without-references
    Optional:    false
  without-references-token-kqll2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  without-references-token-kqll2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node-role.kubernetes.io/compute=true
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
Events:
  Type     Reason     Age                   From                          Message
  ----     ------     ----                  ----                          -------
  Normal   Scheduled  33m                   default-scheduler             Successfully assigned ci-op-8lf9w1d3/without-references-produce-content to origin-ci-ig-n-kgzv
  Normal   Pulling    33m                   kubelet, origin-ci-ig-n-kgzv  pulling image "registry.svc.ci.openshift.org/ci/secret-wrapper:latest"
  Normal   Pulled     32m                   kubelet, origin-ci-ig-n-kgzv  Successfully pulled image "registry.svc.ci.openshift.org/ci/secret-wrapper:latest"
  Normal   Created    32m                   kubelet, origin-ci-ig-n-kgzv  Created container
  Normal   Started    32m                   kubelet, origin-ci-ig-n-kgzv  Started container
  Normal   Pulling    29m                   kubelet, origin-ci-ig-n-kgzv  pulling image "busybox"
  Normal   Pulled     28m                   kubelet, origin-ci-ig-n-kgzv  Successfully pulled image "busybox"
  Normal   Created    28m                   kubelet, origin-ci-ig-n-kgzv  Created container
  Normal   Started    28m                   kubelet, origin-ci-ig-n-kgzv  Started container
  Warning  Failed     26m (x3 over 29m)     kubelet, origin-ci-ig-n-kgzv  Error: ErrImagePull
  Warning  Failed     26m (x3 over 29m)     kubelet, origin-ci-ig-n-kgzv  Failed to pull image "docker-registry.default.svc:5000/ci-op-8lf9w1d3/pipeline@sha256:fe2347002c630d5d61bf2f28f21246ad1c21cc6fd343e70b4cf1e5102f8711a9": rpc error: code = Unknown desc = unauthorized: authentication required
  Normal   Pulling    26m (x4 over 32m)     kubelet, origin-ci-ig-n-kgzv  pulling image "docker-registry.default.svc:5000/ci-op-8lf9w1d3/pipeline@sha256:fe2347002c630d5d61bf2f28f21246ad1c21cc6fd343e70b4cf1e5102f8711a9"
  Normal   BackOff    8m8s (x85 over 28m)   kubelet, origin-ci-ig-n-kgzv  Back-off pulling image "docker-registry.default.svc:5000/ci-op-8lf9w1d3/pipeline@sha256:fe2347002c630d5d61bf2f28f21246ad1c21cc6fd343e70b4cf1e5102f8711a9"
  Warning  Failed     3m4s (x107 over 28m)  kubelet, origin-ci-ig-n-kgzv  Error: ImagePullBackOff
```

**Comment by stevekuznetsov** [comment]
What the fuck is this 

```
2020/08/20 23:54:48 Ran for 0s
error: some steps failed:
  * failed to generate steps from config: failed to resolve release pre: failed to request latest release: server responded with 503: &{%!s(*http.body=&{0xc0007fccc0 <nil> <nil> true false {0 0} false false false <nil>}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error) error=0x7fe100) %!s(func() error=0x7fe080)}
```

**Pull request merged**
