### PR TITLE
Generate flag --image-mirror-push-secret for promotion jobs

### PR DESCRIPTION
**Pull request by hongkailiu**
/hold

will rebase after https://github.com/openshift/ci-tools/pull/1337 is merged.

/cc @stevekuznetsov @alvaroaleman

### CODE REVIEW

**Comment by hongkailiu** [comment]
This is a breaking change.
Need prepare for release repo and another one with the job defs.

**Comment by stevekuznetsov** [comment]
We need to mount the thing too, right? Not just pass a flag

**Review by stevekuznetsov — APPROVED** [review]
Oh, we are already mounting.

**Pull request merged**
