### PR TITLE
convert metadata revision to string and refactor the tests

### PR DESCRIPTION
**Pull request by droslean**
after #252 the jobs couldn't report to testgrid.  This patch is fixing that.

### CODE REVIEW

**Comment by droslean** [comment]
closing... Expecting changes from testgrid side to support both `int` and `string` revisions. 

/close

**Comment by droslean** [comment]
@meowfaceman FYI

**Comment by meowfaceman** [comment]
Sorry about that -- that's an unexpected problem here. Thanks for following up on this.

**Comment by meowfaceman** [comment]
Sorry, so thinking on this: what's the problem, exactly? I would have figured testgrid could have handled this. We're definitely still seeing results here: https://testgrid.k8s.io/redhat-osd-int#osd-int-4.2

**Comment by droslean** [comment]
testgrid magic :D

**Comment by petr-muller** [comment]
> testgrid magic :D

I would be quite interested in more detailed reason too... How was this diagnosed?

**Comment by stevekuznetsov** [comment]
Michelle was able to look at the (internal) logs for the process that reads these files and see the error.

**Comment by droslean** [comment]
> I would be quite interested in more detailed reason too... How was this diagnosed?

@petr-muller Testgrid was able to find the other job because it had another revision that it could read.
check [finished.json](https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-int-4.2/287/finished.json)

**Pull request merged**
