### PR TITLE
fix generator for testgrid file bug template

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
/hold cancel

@smarterclayton let's go ahead and merge this.  `<link>` doesn't work, but it sounds like there's no way to actually get the link to the job today unfortunately.  This fixes the rest of the BZ url at least.

**Comment by bparees** [comment]
corresponding testgrid changes are here: https://github.com/kubernetes/test-infra/pull/16805

**Comment by smarterclayton** [comment]
Cross link your change to test-infra here

**Comment by bparees** [comment]
done

**Pull request merged**
