### PR TITLE
Add Dockerfile for ca-cert-issuer

### PR DESCRIPTION
**Pull request by hongkailiu**
https://jira.coreos.com/browse/DPTP-619

/cc @openshift/openshift-team-developer-productivity-test-platform

### CODE REVIEW

**Comment by hongkailiu** [comment]
> Why? Why not just add a `BuildConfig` in `core-services`?

HAHA ... you know what I have finished BC definition ... but i realized the feeling that @petr-muller prefer ci-operator build than `bc` when i did the ipi image.

OK ... switching back.

**Comment by stevekuznetsov** [comment]
A Dockerfile here and builds every time this repository change makes sense when the content that is in the build depends on this repository or changes with it. The build you had proposed here is static and entirely unrelated to this repository, so it does not belong here. @hongkailiu

**Pull request closed without merging**
