### PR TITLE
bump `prow` dependency

### PR DESCRIPTION
**Pull request by smg247**
Needed to grab: https://github.com/kubernetes-sigs/prow/pull/275

### CODE REVIEW

**Comment by psalajova** [comment]
The failing `validate-prow` job was an issue when we were bumping the ci-tools repo with Danilo a while ago; it demands that release-controller and ci-chat-bot repos need to have their prow versions bumped as well

**Comment by smg247** [comment]
> The failing `validate-prow` job was an issue when we were bumping the ci-tools repo with Danilo a while ago; it demands that release-controller and ci-chat-bot repos need to have their prow versions bumped as well

yes, I took care of that already

**Pull request merged**
