### PR TITLE
Use different secrets and leases for new packet cluster profiles

### PR DESCRIPTION
**Pull request by lranjbar**
We actually need different secrets for the new packet cluster profiles.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Note you'll also need to:

- get the new credentials in Vault (ask `@dptp-helpdesk`)
- get the new secret in the build clusters somehow (see the [existing secret configuration](https://github.com/openshift/release/blob/8bdca56d5bc5f1259bd82fff72395d37ea24b9e9/core-services/ci-secret-bootstrap/_config.yaml#L1425-L1451))
- have a PR in `openshift/release` ready for when this merges (see the result of the [`breaking-changes` job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ci-tools/2309/pull-ci-openshift-ci-tools-master-breaking-changes/1431392629618118656))

/lgtm
/hold

**Comment by lranjbar** [comment]
After some discussions we are adding a new qouta as well.

**Review by AlexNPavel — APPROVED** [review]
/hold cancel

**Pull request merged**
