### PR TITLE
Fix DPTP-2823 Remove package-lock.json

### PR DESCRIPTION
**Pull request by bear-redhat**
Fix [DPTP-2823](https://issues.redhat.com//browse/DPTP-2823) Remove `package-lock.json`. This file was not useful and misled the auto project detection in snyk.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
/hold

What is this file and why is it being removed?

**Comment by bear-redhat** [comment]
> 

We don't know if this file is still useful so I open a PR to see if tests can still pass without it...

**Pull request merged**
