### PR TITLE
Update vendors and add the PreserveOriginal import policy on input image tags

### PR DESCRIPTION
**Pull request by droslean**
This PR:

- Replaces the test-infra library with the forked droslean/test-infra that includes those two changes: https://github.com/droslean/test-infra/pull/1 and https://github.com/droslean/test-infra/pull/2
- Upgrades all k8s vendors to v0.27.2
- Refactor necessary code 
- Upgrades the openshift API package to the latest version.
- Adds the PreserveOriginal import policy on input image tags.
/cc @openshift/test-platform 

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

### CODE REVIEW

**Comment by droslean** [comment]
we need also:
https://github.com/openshift/release/pull/39837 and https://github.com/openshift/release/pull/39831

**Comment by danilo-gemoli** [comment]
leap of faith
/lgtm

**Pull request merged**
