### PR TITLE
ci-operator: upload artifacts with pod-utils by default

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

/assign @alvaroaleman
depends on #1641 
part of [DPTP-1819](https://issues.redhat.com/browse/DPTP-1819)

### CODE REVIEW

**Review by alvaroaleman — APPROVED** [review]
/hold

Can you prepare an o/release PR?

**Comment by stevekuznetsov** [comment]
@alvaroaleman this requires no `o/release` PR

/hold cancel
/retest

**Comment by stevekuznetsov** [comment]
needs https://github.com/openshift/release/pull/15348

**Review by alvaroaleman — APPROVED** [review]

**Comment by stevekuznetsov** [comment]
This somehow broke CLI injection ... lol. Yay for tests

**Review by alvaroaleman — APPROVED** [review]

**Pull request merged**
