### PR TITLE
SPLAT-910: introduce vsphere 8 cluster profile

### PR DESCRIPTION
**Pull request by rvanderp3**
Introducing the vsphere 8 cluster profile to enable testing of CI jobs in the vSphere 8 environment

### CODE REVIEW

**Comment by rvanderp3** [comment]
/assign @bear-redhat 

I opened a bug on the test failures https://issues.redhat.com/browse/DPTP-3260

**Comment by danilo-gemoli** [comment]
@rvanderp3 from my understanding, steps `LeaseTypeFromClusterType()` and `ClusterProfile::ConfigMap()` of [registering-a-new-profile](https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/#registering-a-new-profile) have not been fulfilled. Are you ok with that?

**Comment by rvanderp3** [comment]
/hold

placing a hold to take a quick look based on https://github.com/openshift/ci-tools/pull/3195#issuecomment-1370973635

**Comment by rvanderp3** [comment]
/hold cancel

removing hold; we shouldn't need to update LeaseTypeFromClusterType or ClusterProfile::ConfigMap()

**Pull request merged**
