### PR TITLE
prow-job-dispatcher: save and load job volumes

### PR DESCRIPTION
**Pull request by hongkailiu**
https://issues.redhat.com/browse/DPTP-1520

/cc @alvaroaleman @stevekuznetsov

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@hongkailiu https://issues.redhat.com/browse/DPTP-1520 is titled "Make prow-jop-dispatcher Idempotent", what does that have to do with saving and loading?

**Comment by hongkailiu** [comment]
> @hongkailiu https://issues.redhat.com/browse/DPTP-1520 is titled "Make prow-jop-dispatcher Idempotent", what does that have to do with saving and loading?

It is in the acceptance criterion.
"given an input set of values from Prometheus, ..."
If we query prometheus each time when run the tool, it is highly likely that we got different answers from Prometheus. And then we do dispatch based on the new answers. Dispatching results would be different.

**Comment by alvaroaleman** [comment]
@hongkailiu yes, but there is no "Make sure the input values don't change". There is just "Make sure the output values don't change assuming the same inputs".

**Comment by alvaroaleman** [comment]
@hongkailiu if we end up needing to make sure the prometheus data doesn't change, we can just hardcode an absolute time window to query (i.E. sep 1 - sep 7). But that is an entirely separate discussion from the issue described in the card.

**Comment by hongkailiu** [comment]
/hold

I will come back to this later (after the manual migration).

**Comment by hongkailiu** [comment]
/close
will do anther PR for time frame.

**Pull request closed without merging**
